#!/usr/bin/env python3
"""oracle's session store — the muscle behind its named conversation sessions.

oracle keeps each conversation as a named SESSION whose whole transcript is
persisted as one JSON file. Every store operation runs THROUGH this script,
exactly the way the file tools run through tools/sandbox-fs.py: it takes a
single ROOT directory as argv[1] and holds every session file under it.

WHERE it runs: like the file-tool sandbox, oracle keeps ONE canonical store so
the two machines share one set of sessions rather than a per-machine split ("for
now", his words). oracle's compute is ollama on `top`, so the store lives there
too — on `top` oracle runs this locally; on `book` it runs over the SAME ssh
master tools/ollama-tunnel.sh holds open. This file is pure stdlib on purpose:
top's system python3 runs it over ssh with nothing installed.

PROTOCOL: one JSON request object on stdin, one JSON result object on stdout.
    {"op": "list"}
    -> {"sessions": [{"id","title","updated","turns"}, ...]}   (newest first)
    {"op": "load", "id": "sess-…"}
    -> {"id","title","created","updated","turns": [...]}
    {"op": "search", "query": "words", "limit": 8, "exclude_id": "sess-…"}
    -> {"query", "matches": [{"id","title","updated","turn","who","excerpt"}]}
    {"op": "save", "id": "sess-…", "title": "…", "turns": [...]}
    -> {"ok": true, "id": "…", "title": "…", "updated": <epoch>}
    {"op": "delete", "id": "sess-…"}
    -> {"ok": true}
An error is `{"error": "<reason>"}` with exit 0 — the reason is surfaced to oracle
and shown, never a crash (docs/DESIGN.md §10: report, don't silently fail). The
session id is generated by oracle (a stable `sess-<ms>-<rand>` token), so this
store never mints one; it only validates the id is a safe bare filename.
"""
import json
import os
import re
import sys
import time

#: A session id is a bare filename component — oracle generates it, we only
#: guard it so a crafted id cannot escape the store directory.
ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
TITLE_MAX = 200          # a title is a one-line label; clip an absurd one
TURNS_MAX = 5000         # refuse a runaway transcript outright
SEARCH_LIMIT_MAX = 20
SEARCH_EXCERPT = 360


def fail(reason):
    print(json.dumps({"error": reason}))
    sys.exit(0)


def path_for(root, sid):
    if not ID_RE.match(sid or "") or ".." in sid:
        fail("bad session id: " + str(sid))
    return os.path.join(root, sid + ".json")


def op_list(root):
    out = []
    try:
        names = os.listdir(root)
    except OSError:
        names = []
    for name in names:
        if not name.endswith(".json"):
            continue
        p = os.path.join(root, name)
        try:
            obj = json.loads(open(p, encoding="utf-8").read() or "{}")
        except (OSError, ValueError):
            continue
        if not isinstance(obj, dict):
            continue
        turns = obj.get("turns")
        out.append({
            "id": obj.get("id", name[:-5]),
            "title": obj.get("title", "") or name[:-5],
            "updated": obj.get("updated", 0),
            "turns": len(turns) if isinstance(turns, list) else 0,
        })
    out.sort(key=lambda s: s.get("updated", 0), reverse=True)
    return {"sessions": out}


def op_load(root, req):
    p = path_for(root, req.get("id", ""))
    try:
        obj = json.loads(open(p, encoding="utf-8").read() or "{}")
    except OSError:
        fail("no such session")
    except ValueError:
        fail("session file is corrupt")
    if not isinstance(obj, dict):
        fail("session file is corrupt")
    return {
        "id": obj.get("id", req.get("id", "")),
        "title": obj.get("title", ""),
        "created": obj.get("created", 0),
        "updated": obj.get("updated", 0),
        "turns": obj.get("turns", []) if isinstance(obj.get("turns"), list) else [],
    }


def op_search(root, req):
    """Bounded lexical retrieval over the authoritative transcript text.

    Exact phrases rank above token hits. Results are verbatim excerpts with
    enough identity to open the full session; no generated summary becomes a
    second, lossy history.
    """
    query = " ".join(str(req.get("query") or "").split())
    if not query:
        fail("search needs a query")
    try:
        limit = max(1, min(int(req.get("limit") or 8), SEARCH_LIMIT_MAX))
    except (TypeError, ValueError):
        limit = 8
    phrase = query.casefold()
    terms = list(dict.fromkeys(re.findall(r"[\w'-]+", phrase)))
    exclude = str(req.get("exclude_id") or "")
    matches = []
    try:
        names = os.listdir(root)
    except OSError:
        names = []
    for name in names:
        if not name.endswith(".json"):
            continue
        try:
            obj = json.loads(open(os.path.join(root, name), encoding="utf-8").read())
        except (OSError, ValueError):
            continue
        if not isinstance(obj, dict) or obj.get("id", name[:-5]) == exclude:
            continue
        sid = obj.get("id", name[:-5])
        title = obj.get("title", "") or sid
        for turn_i, turn in enumerate(obj.get("turns") or []):
            if not isinstance(turn, dict):
                continue
            body = str(turn.get("body") or turn.get("content") or "")
            low = body.casefold()
            hits = sum(low.count(t) for t in terms)
            if not hits:
                continue
            pos = low.find(phrase)
            score = hits + (100 if pos >= 0 else 0)
            if pos < 0:
                pos = min((low.find(t) for t in terms if t in low), default=0)
            start = max(0, pos - SEARCH_EXCERPT // 3)
            end = min(len(body), start + SEARCH_EXCERPT)
            excerpt = body[start:end]
            if start:
                excerpt = "…" + excerpt
            if end < len(body):
                excerpt += "…"
            matches.append({"id": sid, "title": title,
                            "updated": obj.get("updated", 0), "turn": turn_i,
                            "who": turn.get("who") or
                                   ("you" if turn.get("isUser") else "assistant"),
                            "excerpt": excerpt, "_score": score})
    matches.sort(key=lambda m: (m["_score"], m.get("updated", 0)), reverse=True)
    for match in matches[:limit]:
        match.pop("_score", None)
    return {"query": query, "matches": matches[:limit]}


def op_save(root, req):
    sid = req.get("id", "")
    p = path_for(root, sid)
    turns = req.get("turns")
    if not isinstance(turns, list):
        fail("save needs a turns array")
    if len(turns) > TURNS_MAX:
        fail("transcript too long")
    title = str(req.get("title", ""))[:TITLE_MAX]
    now = int(time.time())
    created = now
    try:                              # preserve the original created stamp
        old = json.loads(open(p, encoding="utf-8").read() or "{}")
        if isinstance(old, dict) and old.get("created"):
            created = old["created"]
    except (OSError, ValueError):
        pass
    obj = {"id": sid, "title": title, "created": created,
           "updated": now, "turns": turns}
    try:
        os.makedirs(root, exist_ok=True)
        tmp = p + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(obj, fh, ensure_ascii=False)
        os.replace(tmp, p)            # atomic, so a reader never sees a half-write
    except OSError as e:
        fail("could not save session: " + str(e))
    return {"ok": True, "id": sid, "title": title, "updated": now}


def op_delete(root, req):
    p = path_for(root, req.get("id", ""))
    try:
        os.remove(p)
    except FileNotFoundError:
        pass
    except OSError as e:
        fail("could not delete session: " + str(e))
    return {"ok": True}


def main():
    if len(sys.argv) < 2:
        fail("usage: sessions-store.py <root>  (JSON request on stdin)")
    root = os.path.realpath(os.path.expanduser(sys.argv[1]))
    try:
        req = json.loads(sys.stdin.read() or "{}")
    except ValueError:
        fail("request is not valid JSON")
    if not isinstance(req, dict):
        fail("request must be a JSON object")
    op = req.get("op", "")
    handler = {"list": lambda: op_list(root),
               "load": lambda: op_load(root, req),
               "search": lambda: op_search(root, req),
               "save": lambda: op_save(root, req),
               "delete": lambda: op_delete(root, req)}.get(op)
    if handler is None:
        fail("unknown op: " + str(op))
    print(json.dumps(handler(), ensure_ascii=False))


if __name__ == "__main__":
    main()
