#!/usr/bin/env python3
"""Generate the Tampermonkey userscript that puts this desktop's look on 4chan
in Vivaldi.

surfer gets the OneeChan override sheet through its own `surferonee://`
courier, in-process, live. Vivaldi cannot: it is somebody else's browser, it
has no Stylus, and the only injection seat available is Tampermonkey — where
OneeChan itself already lives. So the same sheet (`pylib/chantheme.py`, shared
verbatim, which is why that module is Qt-free) is BAKED into a userscript here.

Baked, therefore stale by design: re-run this after changing the KDE colour
scheme or the wallpaper, and Tampermonkey picks the new file up on its next
update check (or reinstall it by hand).

    apps/pylib/tools/chan-userscript.py            # write it, print the path
    apps/pylib/tools/chan-userscript.py --stdout   # print the script instead
    apps/pylib/tools/chan-userscript.py --css      # just the CSS
    apps/pylib/tools/chan-userscript.py --source hypr|plasma

The palette source follows the same rule the apps do (`kdetheme.is_plasma`):
the KDE colour scheme in a Plasma session — with the KStyle's gradients and
bevels on top when the style draws them — and the panel's wallpaper palette in
the Hyprland one, where DESIGN.md §2's "no gradients" holds and the sheet stays
flat. `--source` forces either, for a look at the other face.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import chantheme                                                # noqa: E402
import kdetheme                                                 # noqa: E402

PANEL_THEME = Path.home() / ".config" / "quickshell" / "Theme.qml"
OUT = Path(os.environ.get("XDG_DATA_HOME") or (Path.home() / ".local" / "share")) \
    / "chan-theme" / "desktop-4chan.user.js"

# `readonly property color bg: "#000000"` — the panel's palette literals, the
# same shape every app's Palette parses (and the same one kdetheme writes).
_COLOR = re.compile(r'property\s+color\s+(\w+)\s*:\s*"(#[0-9a-fA-F]{3,8})"')


def panel_palette(path=PANEL_THEME) -> dict:
    out = {}
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return out
    for name, value in _COLOR.findall(text):
        out.setdefault(name, value[:7])
    return out


def build_css(source=None):
    """(css, provenance) for the requested session face."""
    plasma = kdetheme.is_plasma() if source is None else (source == "plasma")
    if plasma:
        colors = kdetheme.kde_palette()
        if colors:
            pal = {k: kdetheme._hex(v) for k, v in colors.items()}
            chrome = kdetheme.kde_chrome()
            style = chrome["style"] if chrome else kdetheme.kde_widget_style()
            return (chantheme.css(pal.__getitem__, chrome),
                    "KDE colour scheme (%s, %s)"
                    % (style or "unknown style",
                       "with the style's relief" if chrome else "flat style"))
    pal = panel_palette()
    if not pal:
        raise SystemExit("no palette: neither a readable kdeglobals nor %s" % PANEL_THEME)
    return (chantheme.css(pal.__getitem__, None),
            "panel wallpaper palette (flat, per DESIGN.md §2)")


HEADER = """\
// ==UserScript==
// @name         desktop 4chan
// @namespace    https://github.com/meatcrowning/nix
// @version      %(version)s
// @description  Re-skins OneeChan's 4chan theme to this desktop's palette (%(prov)s). Generated by ~/nix/apps/pylib/tools/chan-userscript.py — do not hand-edit, re-run it.
// @author       lam
// @match        *://boards.4chan.org/*
// @match        *://boards.4channel.org/*
// @run-at       document-start
// @grant        none
// @downloadURL  file://%(path)s
// @updateURL    file://%(path)s
// ==/UserScript==
"""

# The runtime is ONEE_THEME_RUNTIME_JS minus the courier: same self-gate on
# `html.oneechan`, same adoptedStyleSheets adoption (which is what puts us after
# ch4SS in the cascade with nothing to out-specify), same ~60s poll cap. The CSS
# is a constant here instead of an XHR, because a userscript has no Python to
# ask.
BODY = """
(function(){
  'use strict';
  if (window.__deskChanTheme) return;
  window.__deskChanTheme = true;

  var CSS = %(css)s;
  var sheet = null;

  function apply(){
    try {
      if (!sheet){
        sheet = new CSSStyleSheet();
        document.adoptedStyleSheets = document.adoptedStyleSheets.concat([sheet]);
      }
      sheet.replaceSync(CSS);
    } catch(e){
      // No constructable stylesheets: fall back to a <style> appended LAST,
      // which still lands after ch4SS as long as OneeChan is already up — and
      // the gate below guarantees it is.
      try {
        var el = document.createElement('style');
        el.id = 'desk-chan-theme';
        el.textContent = CSS;
        (document.head || document.documentElement).appendChild(el);
      } catch(e2){}
    }
  }

  function active(){
    try {
      return !!(document.documentElement &&
                document.documentElement.classList.contains('oneechan'));
    } catch(e){ return false; }
  }

  // OneeChan marks the page after document-start, so poll for html.oneechan
  // and only then adopt — the re-skin rides ONLY while OneeChan is on, never
  // on bare 4chan.
  var tries = 0;
  var iv = setInterval(function(){
    tries++;
    if (active()){ apply(); clearInterval(iv); }
    else if (tries > 600){ clearInterval(iv); }
  }, 100);
})();
"""


def build(source=None, path=OUT):
    css, prov = build_css(source)
    # A version that moves whenever the colours do, so Tampermonkey's update
    # check has something to compare (it refuses to install a same-or-older
    # version). Content-derived, not a clock: regenerating an unchanged palette
    # must not churn.
    version = "1.0.%d" % (zlib.crc32(css.encode("utf-8")) % 100000)
    return (HEADER % {"version": version, "prov": prov, "path": path}
            + BODY % {"css": json.dumps(css)}), prov


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", choices=("hypr", "plasma"),
                    help="force the palette source instead of the live session")
    ap.add_argument("--stdout", action="store_true", help="print, do not write")
    ap.add_argument("--css", action="store_true", help="print the CSS only")
    ap.add_argument("-o", "--out", type=Path, default=OUT)
    a = ap.parse_args()
    if a.css:
        print(build_css(a.source)[0])
        return 0
    text, prov = build(a.source, a.out)
    if a.stdout:
        sys.stdout.write(text)
        return 0
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(text, encoding="utf-8")
    print("%s\n  from: %s\n  open file://%s in Vivaldi to (re)install"
          % (a.out, prov, a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
