#!/usr/bin/env python3
"""Generate the Tampermonkey userscript that puts this desktop's look on 4chan
in Vivaldi.

surfer gets the OneeChan override sheet through its own `surferonee://`
courier, in-process, live. Vivaldi cannot: it is somebody else's browser, it
has no Stylus, and the only injection seat available is Tampermonkey — where
OneeChan itself already lives. So the same sheet (`pylib/chantheme.py`, shared
verbatim, which is why that module is Qt-free) goes into a userscript here.

NOT baked-only any more. The script asks `tools/chan-theme-server.py` — a
loopback courier on 127.0.0.1 — for the current sheet, and re-adopts it when
the ETag moves, so a colour-scheme or wallpaper change repaints an OPEN 4chan
tab within the poll interval and needs no regeneration at all. The sheet built
here is still embedded, as the fallback for a page loaded while the courier is
down; a 4chan page is https, so the fetch must go through GM_xmlhttpRequest
(mixed content blocks a plain one), which is what the `@grant` and `@connect`
lines below are for.

Re-run this only when the SHEET (`pylib/chantheme.py`) or this generator
changes — not for a palette change. Tampermonkey picks the new file up on its
next update check (or reinstall it by hand).

    apps/pylib/tools/chan-userscript.py            # write it, print the path
    apps/pylib/tools/chan-userscript.py --stdout   # print the script instead
    apps/pylib/tools/chan-userscript.py --css      # just the CSS
    apps/pylib/tools/chan-userscript.py --source hypr|plasma

The palette source follows the same rule the apps do (`kdetheme.is_plasma`):
the KDE colour scheme in a Plasma session — with the KStyle's gradients and
bevels on top when the style draws them — and the panel's wallpaper palette in
the Hyprland one, where DESIGN.md §2's "no gradients" holds and the sheet stays
flat. `--source` forces either, for a look at the other face; it also pins the
courier the script polls, so a `--source`-built script asks for that same face.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import chansource                                               # noqa: E402

build_css = chansource.build_css
panel_palette = chansource.panel_palette
PANEL_THEME = chansource.PANEL_THEME
OUT = Path(os.environ.get("XDG_DATA_HOME") or (Path.home() / ".local" / "share")) \
    / "chan-theme" / "desktop-4chan.user.js"


HEADER = """\
// ==UserScript==
// @name         desktop 4chan
// @namespace    https://github.com/meatcrowning/nix
// @version      %(version)s
// @description  Re-skins OneeChan's 4chan theme to this desktop's LIVE palette (%(prov)s), polling the loopback courier. Generated by ~/nix/apps/pylib/tools/chan-userscript.py — do not hand-edit, re-run it.
// @author       lam
// @match        *://boards.4chan.org/*
// @match        *://boards.4channel.org/*
// @run-at       document-start
// @grant        GM_xmlhttpRequest
// @connect      127.0.0.1
// @connect      localhost
// @downloadURL  file://%(path)s
// @updateURL    file://%(path)s
// ==/UserScript==
"""

# The runtime is ONEE_THEME_RUNTIME_JS with a different courier: same self-gate
# on `html.oneechan`, same adoptedStyleSheets adoption (which is what puts us
# after ch4SS in the cascade with nothing to out-specify), same ~60s wait cap.
#
# Where surfer asks Python over `surferonee://`, this asks the same Python over
# 127.0.0.1 (tools/chan-theme-server.py) through GM_xmlhttpRequest — a plain
# fetch() cannot, a 4chan page being https and http://127.0.0.1 mixed content.
# The baked sheet stays as the fallback for a page loaded while the courier is
# down, so the re-skin never degrades to bare OneeChan colours.
#
# It POLLS rather than being pushed to, because the pusher would have to be
# wal-set.sh reaching into somebody else's browser, which it has no seat in.
# One conditional GET every %(poll)ss per open 4chan tab, on loopback, answered
# 304 whenever the palette has not moved.
BODY = r"""
(function(){
  'use strict';
  if (window.__deskChanTheme) return;
  window.__deskChanTheme = true;

  var URL = %(url)s;
  var POLL = %(poll)d * 1000;
  var CSS = %(css)s;            // baked fallback: the palette at bake time
  var stamp = null;             // the courier's ETag for what is adopted now
  var sheet = null;

  function apply(css){
    try {
      if (!sheet){
        sheet = new CSSStyleSheet();
        document.adoptedStyleSheets = document.adoptedStyleSheets.concat([sheet]);
      }
      sheet.replaceSync(css);
      return;
    } catch(e){}
    // No constructable stylesheets: fall back to a <style> appended LAST,
    // which still lands after ch4SS as long as OneeChan is already up — and
    // the gate below guarantees it is.
    try {
      var el = document.getElementById('desk-chan-theme');
      if (!el){
        el = document.createElement('style');
        el.id = 'desk-chan-theme';
        (document.head || document.documentElement).appendChild(el);
      }
      el.textContent = css;
    } catch(e2){}
  }

  // GM_xmlhttpRequest, not fetch: https page, http loopback courier.
  function pull(){
    var headers = stamp ? { 'If-None-Match': stamp } : {};
    try {
      GM_xmlhttpRequest({
        method: 'GET', url: URL, headers: headers, timeout: 4000,
        onload: function(r){
          if (r.status === 304) return;              // palette has not moved
          if (r.status !== 200 || !r.responseText) return;
          var tag = null;
          try {
            tag = /etag:\s*(\S+)/i.exec(r.responseHeaders || '');
            tag = tag && tag[1];
          } catch(e){}
          stamp = tag;
          apply(r.responseText);
        },
        onerror: function(){}, ontimeout: function(){}
      });
    } catch(e){}                                     // no grant: stay on baked
  }

  function active(){
    try {
      return !!(document.documentElement &&
                document.documentElement.classList.contains('oneechan'));
    } catch(e){ return false; }
  }

  // OneeChan marks the page after document-start, so poll for html.oneechan
  // and only then adopt — the re-skin rides ONLY while OneeChan is on, never
  // on bare 4chan. The baked sheet goes on first so there is never a frame of
  // OneeChan's own colours while the courier answers.
  var tries = 0;
  var iv = setInterval(function(){
    tries++;
    if (active()){
      clearInterval(iv);
      apply(CSS);
      pull();
      setInterval(pull, POLL);                       // live: repaint on change
    } else if (tries > 600){ clearInterval(iv); }
  }, 100);
})();
"""

# Long enough that an idle tab is doing nothing measurable, short enough that a
# wallpaper change lands while he is still looking at the result.
POLL_SECONDS = 30


def build(source=None, path=OUT, port=None):
    css, prov = build_css(source)
    port = port or chansource.PORT
    # A version that moves whenever the SHEET does, so Tampermonkey's update
    # check has something to compare (it refuses to install a same-or-older
    # version). Content-derived, not a clock: regenerating an unchanged palette
    # must not churn.
    version = "2.0.%s" % chansource.stamp(css)
    return (HEADER % {"version": version, "prov": prov, "path": path}
            + BODY % {"css": json.dumps(css),
                      "url": json.dumps("http://127.0.0.1:%d/chan.css" % port),
                      "poll": POLL_SECONDS}), prov


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", choices=("hypr", "plasma"),
                    help="force the palette source instead of the live session")
    ap.add_argument("--stdout", action="store_true", help="print, do not write")
    ap.add_argument("--css", action="store_true", help="print the CSS only")
    ap.add_argument("--port", type=int, default=chansource.PORT,
                    help="the loopback courier the script polls")
    ap.add_argument("-o", "--out", type=Path, default=OUT)
    a = ap.parse_args()
    if a.css:
        print(build_css(a.source)[0])
        return 0
    text, prov = build(a.source, a.out, a.port)
    if a.stdout:
        sys.stdout.write(text)
        return 0
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(text, encoding="utf-8")
    print("%s\n  live from: http://127.0.0.1:%d/chan.css (chan-theme-server)"
          "\n  baked fallback: %s\n  open file://%s in Vivaldi to (re)install"
          % (a.out, a.port, prov, a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
