#!/usr/bin/env python3
"""Konsole's colours, generated from whatever this session calls the theme.

Konsole is a KDE app with its own private palette: a `.colorscheme` file
picked per profile, which follows neither `kdeglobals` nor the panel. So the
one terminal on this box that is not kitty drew Breeze grey on a desktop that
had gone green, and every wallpaper change left it behind.

This writes that file. The source is the same rule every other consumer here
follows (`kdetheme.is_plasma()`, and `pylib/chansource.py` for the 4chan
sheet): the KDE colour scheme in a Plasma session, the panel's
wallpaper-derived `Theme.qml` in the Hyprland one. Both are "the system
theme" — which one that means is a property of the session, not a setting.

    ~/.local/share/konsole/Dynamic.colorscheme    <- written here, ours
    ~/.local/share/konsole/<default>.profile      <- one key patched: ColorScheme

The ANSI mapping is kitty's, deliberately (wal-set.sh step 4): foreground and
the two "white" slots are ACCENT rather than TEXT, so terminal body text
matches the focused window's titlebar, and the ramp is monochrome on the
wallpaper's hue with only the four status colours breaking out.

    konsole-theme            # write it, patch the default profile, poke konsole
    konsole-theme --print    # print the scheme, touch nothing
    konsole-theme --source plasma|hypr
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import chansource                                               # noqa: E402
import kdetheme                                                 # noqa: E402

SCHEME_NAME = "Dynamic"
KONSOLE_DIR = Path(os.environ.get("KONSOLE_THEME_DIR")
                   or (Path.home() / ".local" / "share" / "konsole"))
KONSOLERC = Path(os.environ.get("KONSOLE_THEME_RC")
                 or (Path.home() / ".config" / "konsolerc"))


# ---- palette -----------------------------------------------------------------

def palette(source=None):
    """(tokens, provenance) — the twelve `#rrggbb` tokens for this session."""
    plasma = kdetheme.is_plasma() if source is None else (source == "plasma")
    if plasma:
        kde = kdetheme.kde_palette()
        if kde:
            return ({k: kdetheme._hex(v) for k, v in kde.items()},
                    "KDE colour scheme (%s)" % (kdetheme.kde_widget_style() or "unknown style"))
    pal = chansource.panel_palette()
    if not pal:
        raise SystemExit("konsole-theme: no palette — neither a readable "
                         "kdeglobals nor %s" % chansource.PANEL_THEME)
    return (pal, "panel wallpaper palette")


def _rgb(h):
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _mix(a, b, t):
    return tuple(round(x + (y - x) * t) for x, y in zip(a, b))


def _kc(rgb):
    return "%d,%d,%d" % rgb


# ---- the scheme --------------------------------------------------------------

def build(pal: dict) -> str:
    """Konsole wants three tones per slot: the colour, a FAINT one and an
    INTENSE one. Nothing in the wal palette carries those, so they are derived
    the way a terminal expects them to read — faint sunk a third of the way
    into the background, intense lifted a third of the way out of it — rather
    than left equal, which makes `bold` and `dim` indistinguishable."""
    g = lambda k, d="#000000": _rgb(pal.get(k, d))                # noqa: E731
    bg, bgAlt = g("bg"), g("bgAlt", "#000000")
    accent, text, textDim = g("accent", "#ffffff"), g("text", "#ffffff"), g("textDim", "#aaaaaa")
    dim, border = g("dim", "#555555"), g("border", "#333333")
    ok, warn, crit, info = g("ok", "#45b27e"), g("warn", "#a8844e"), g("crit", "#d96262"), g("info", "#475c99")
    white = _mix(bg, (255, 255, 255), 0.98)

    def slot(n, color, faint=None, intense=None):
        out.append("[Color%d]\nColor=%s\n" % (n, _kc(color)))
        out.append("[Color%dFaint]\nColor=%s\n" % (n, _kc(faint if faint else _mix(color, bg, 0.35))))
        out.append("[Color%dIntense]\nColor=%s\n" % (n, _kc(intense if intense else _mix(color, white, 0.35))))

    out = ["# GENERATED by konsole-theme (apps/pylib/tools/konsole-theme.py).\n"
           "# Edits are overwritten on the next theme or wallpaper change.\n\n"]
    out.append("[Background]\nColor=%s\n" % _kc(bg))
    out.append("[BackgroundFaint]\nColor=%s\n" % _kc(bg))
    out.append("[BackgroundIntense]\nColor=%s\n" % _kc(bgAlt))
    out.append("[Foreground]\nColor=%s\n" % _kc(accent))
    out.append("[ForegroundFaint]\nColor=%s\n" % _kc(textDim))
    out.append("[ForegroundIntense]\nColor=%s\n" % _kc(_mix(accent, white, 0.35)))
    slot(0, bg, faint=bg, intense=dim)          # black
    slot(1, crit)
    slot(2, ok)
    slot(3, warn)
    slot(4, info)
    slot(5, textDim, intense=text)              # magenta -> the text tone
    slot(6, accent)
    slot(7, accent, faint=border, intense=accent)   # white == body text, as in kitty
    out.append("[General]\nBlur=false\nColorRandomization=false\n"
               "Description=%s\nOpacity=1\nWallpaper=\n" % SCHEME_NAME)
    return "".join(out)


# ---- the profile -------------------------------------------------------------

def default_profile() -> Path | None:
    """The profile konsolerc calls default, or None when konsole is still on
    its built-in one (which lives in no file and cannot be patched)."""
    try:
        rc = KONSOLERC.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    m = re.search(r"^DefaultProfile=(.+)$", rc, re.M)
    if not m:
        return None
    p = KONSOLE_DIR / m.group(1).strip()
    return p if p.exists() else None


def write_profile(path: Path, pal: dict) -> None:
    """Create the profile we are about to make default. Font matches kitty's
    (docs/DESIGN.md §1) — the pixel font at the same size the rest of the
    desktop uses — because a new profile with no font gets a stock Monospace
    that matches nothing else on screen."""
    path.write_text(
        "[Appearance]\n"
        "AntiAliasFonts=true\n"
        "BoldIntense=true\n"
        "ColorScheme=%s\n"
        "Font=More Perfect DOS VGA,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0\n"
        "\n[General]\nName=%s\nParent=FALLBACK/\n"
        "\n[Scrolling]\nScrollBarPosition=2\n"
        "\n[Terminal Features]\nBlinkingCursorEnabled=true\n" % (SCHEME_NAME, SCHEME_NAME),
        encoding="utf-8")


def patch_profile(path: Path) -> bool:
    """Set ColorScheme in HIS profile and touch nothing else in it — the rest
    of that file (font, scrollback, keys) is his."""
    text = path.read_text(encoding="utf-8", errors="replace")
    new, n = re.subn(r"^ColorScheme=.*$", "ColorScheme=" + SCHEME_NAME, text, count=1, flags=re.M)
    if n == 0:
        if re.search(r"^\[Appearance\]$", text, re.M):
            new = re.sub(r"^\[Appearance\]$", "[Appearance]\nColorScheme=" + SCHEME_NAME,
                         text, count=1, flags=re.M)
        else:
            new = "[Appearance]\nColorScheme=%s\n\n%s" % (SCHEME_NAME, text)
    if new == text:
        return False
    path.write_text(new, encoding="utf-8")
    return True


def set_default(name: str) -> None:
    """konsolerc's [Desktop Entry] DefaultProfile, written by hand rather than
    with kwriteconfig6 so this works with nothing from KDE on PATH."""
    try:
        text = KONSOLERC.read_text(encoding="utf-8", errors="replace")
    except OSError:
        text = ""
    line = "DefaultProfile=" + name
    if re.search(r"^DefaultProfile=", text, re.M):
        text = re.sub(r"^DefaultProfile=.*$", line, text, count=1, flags=re.M)
    elif re.search(r"^\[Desktop Entry\]$", text, re.M):
        text = re.sub(r"^\[Desktop Entry\]$", "[Desktop Entry]\n" + line, text, count=1, flags=re.M)
    else:
        text = (text.rstrip("\n") + "\n\n" if text else "") + "[Desktop Entry]\n" + line + "\n"
    KONSOLERC.parent.mkdir(parents=True, exist_ok=True)
    KONSOLERC.write_text(text, encoding="utf-8")


# ---- live konsoles -----------------------------------------------------------

def poke() -> int:
    """Re-apply the profile on every running session, over konsole's own D-Bus
    interface. Best effort and deliberately quiet: konsole caches a colour
    scheme by name for the life of the process, so a window that was already
    open may keep the old colours until it is reopened — a new window always
    gets the new ones. Never raises; a terminal that will not repaint is not a
    reason for the theme apply to fail."""
    qdbus = None
    for c in ("qdbus", "qdbus6"):
        try:
            subprocess.run([c, "--version"], capture_output=True, timeout=5)
            qdbus = c
            break
        except (OSError, subprocess.SubprocessError):
            continue
    if qdbus is None:
        return 0
    n = 0
    try:
        services = subprocess.run([qdbus], capture_output=True, text=True, timeout=5).stdout
    except (OSError, subprocess.SubprocessError):
        return 0
    for svc in services.split():
        if not svc.startswith("org.kde.konsole"):
            continue
        try:
            sessions = subprocess.run([qdbus, svc], capture_output=True, text=True,
                                      timeout=5).stdout
            for obj in sessions.split():
                if not re.fullmatch(r"/Sessions/\d+", obj):
                    continue
                cur = subprocess.run([qdbus, svc, obj, "org.kde.konsole.Session.profile"],
                                     capture_output=True, text=True, timeout=5).stdout.strip()
                subprocess.run([qdbus, svc, obj, "org.kde.konsole.Session.setProfile",
                                cur or SCHEME_NAME],
                               capture_output=True, timeout=5)
                n += 1
        except (OSError, subprocess.SubprocessError):
            continue
    return n


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", choices=("hypr", "plasma"),
                    help="force the palette source instead of the live session")
    ap.add_argument("--print", dest="dump", action="store_true",
                    help="print the scheme and exit, writing nothing")
    ap.add_argument("--no-default", action="store_true",
                    help="write the scheme but leave the default profile alone")
    a = ap.parse_args()

    pal, prov = palette(a.source)
    scheme = build(pal)
    if a.dump:
        sys.stderr.write("konsole-theme: from %s\n" % prov)
        sys.stdout.write(scheme)
        return 0

    KONSOLE_DIR.mkdir(parents=True, exist_ok=True)
    dest = KONSOLE_DIR / ("%s.colorscheme" % SCHEME_NAME)
    if not dest.exists() or dest.read_text(encoding="utf-8", errors="replace") != scheme:
        dest.write_text(scheme, encoding="utf-8")

    if not a.no_default:
        prof = default_profile()
        if prof is None:
            prof = KONSOLE_DIR / ("%s.profile" % SCHEME_NAME)
            if not prof.exists():
                write_profile(prof, pal)
            set_default(prof.name)
        patch_profile(prof)
        sys.stderr.write("konsole-theme: %s from %s, default profile %s\n"
                         % (dest.name, prov, prof.name))
    else:
        sys.stderr.write("konsole-theme: %s from %s\n" % (dest.name, prov))
    poke()
    return 0


if __name__ == "__main__":
    sys.exit(main())
