#!/usr/bin/env python3
"""Generate the Tampermonkey userscript that puts this desktop's scrollbar on
every page in Vivaldi — and the `custom.css` that puts it on Vivaldi's own UI.

Chromium never asks Qt or GTK for a scrollbar; it paints its own in Aura. So a
page's bar is the one control `qmlcommon/VScroll.qml` cannot reach, and in
Vivaldi neither can a Qt style: no Stylus, no theme bridge, only Tampermonkey.
`pylib/scrollcss.py` builds the sheet (Oxygen's own bar under Plasma, the
desktop's win31/beveled/flat variant otherwise) and this puts it where Vivaldi
will read it. Both halves are LIVE against the loopback courier the same way
the 4chan sheet is — see `pylib/userscript.py`.

TWO SURFACES, and only one of them can poll:

    --script   ~/.local/share/chan-theme/desktop-scrollbar.user.js
               every page, re-adopted within POLL_SECONDS of a palette change.

    --ui       ~/.local/share/vivaldi-ui/custom.css
               Vivaldi's OWN interface (panels, settings, tab stack), which is
               a Chromium page too. Enable it once at vivaldi://experiments ->
               "Allow for using CSS modifications", then point Settings ->
               Appearance -> "Custom UI Modifications" at that FOLDER. It is
               read at startup, so a palette change reaches the UI at the next
               Vivaldi launch; wal-set.sh rewrites the file so it is never
               stale when that happens.

    apps/pylib/tools/scrollbar-userscript.py            # write both
    apps/pylib/tools/scrollbar-userscript.py --css      # print the CSS only
    apps/pylib/tools/scrollbar-userscript.py --source hypr|plasma
    apps/pylib/tools/scrollbar-userscript.py --style win31|beveled|flat
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import chansource                                               # noqa: E402
import scrollcss                                                # noqa: E402
import userscript                                               # noqa: E402

DATA = Path(os.environ.get("XDG_DATA_HOME") or (Path.home() / ".local" / "share"))
OUT = DATA / "chan-theme" / "desktop-scrollbar.user.js"
UI_DIR = DATA / "vivaldi-ui"

# Everything http(s), including a local file:// page — the desktop's scrollbar
# is not a per-site opinion.
MATCHES = ("*://*/*", "file:///*")


def build(source=None, style=None, path=OUT, port=None):
    css, prov = scrollcss.build(source, style)
    port = port or chansource.PORT
    version = "1.0.%s" % chansource.stamp(css)
    return userscript.build(
        name="desktop scrollbar",
        description=("Draws every page's scrollbar as this desktop's (%s), "
                     "polling the loopback courier." % prov),
        matches=MATCHES, css=css, version=version,
        url="http://127.0.0.1:%d/scrollbar.css" % port,
        key="__deskScrollbar", style_id="desk-scrollbar",
        path=path, tool="scrollbar-userscript.py"), prov


UI_HEADER = """\
/* Vivaldi's own UI, wearing this desktop's scrollbar (%s).
 * Generated by ~/nix/apps/pylib/tools/scrollbar-userscript.py --ui — do not
 * hand-edit, re-run it (wal-set.sh does, on every palette change).
 * Read at Vivaldi startup only: a change here shows at the next launch. */
"""


def write_ui(source=None, style=None, directory=UI_DIR):
    css, prov = scrollcss.build(source, style)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "custom.css"
    text = UI_HEADER % prov + css + "\n"
    # Unchanged content is not rewritten: wal-set.sh calls this on every run.
    try:
        if path.read_text(encoding="utf-8") == text:
            return path, prov, False
    except OSError:
        pass
    path.write_text(text, encoding="utf-8")
    return path, prov, True


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", choices=("hypr", "plasma"),
                    help="force the palette source instead of the live session")
    ap.add_argument("--style", choices=scrollcss.STYLES,
                    help="force a desktop variant instead of the settings pick")
    ap.add_argument("--script", action="store_true", help="write only the userscript")
    ap.add_argument("--ui", action="store_true", help="write only Vivaldi's custom.css")
    ap.add_argument("--css", action="store_true", help="print the CSS, write nothing")
    ap.add_argument("--stdout", action="store_true", help="print the userscript")
    ap.add_argument("--port", type=int, default=chansource.PORT)
    ap.add_argument("-o", "--out", type=Path, default=OUT)
    a = ap.parse_args()

    if a.css:
        print(scrollcss.build(a.source, a.style)[0])
        return 0
    text, prov = build(a.source, a.style, a.out, a.port)
    if a.stdout:
        sys.stdout.write(text)
        return 0

    both = not (a.script or a.ui)
    if a.script or both:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(text, encoding="utf-8")
        print("%s\n  live from: http://127.0.0.1:%d/scrollbar.css (chan-theme-server)"
              "\n  embedded fallback: %s\n  open file://%s in Vivaldi to (re)install"
              % (a.out, a.port, prov, a.out))
    if a.ui or both:
        path, prov, changed = write_ui(a.source, a.style)
        print("%s\n  %s\n  vivaldi://experiments -> allow CSS modifications, then"
              " Settings > Appearance > Custom UI Modifications = %s"
              % (path, "rewritten" if changed else "unchanged", path.parent))
    return 0


if __name__ == "__main__":
    sys.exit(main())
