#!/usr/bin/env python3
"""Put this desktop's look on Vivaldi's own interface.

Vivaldi's UI is a Chromium page whose every colour comes from about ninety CSS
custom properties (`pylib/vivaldichrome.py` builds them from the live palette),
so the browser can be re-themed the way a web page is — no patched build, and
no source to build even if one wanted to. Two surfaces, written here:

    --ui      ~/.local/share/vivaldi-ui/custom.css
              The colour ladder, Oxygen's relief on the surfaces that have one
              (header, toolbar, tabs, address field, buttons) and the page
              scrollbar sheet, in one file. Enable it once at
              `vivaldi://experiments` -> "Allow for using CSS modifications",
              then Settings > Appearance > Custom UI Modifications -> that
              FOLDER. Read at startup: a change shows at the next launch, and
              the `vivaldi-ui-css` path unit keeps it current in the meantime.

    --prefs   the theme entry in ~/.config/vivaldi/Default/Preferences
              Vivaldi decides for itself whether its UI is light or dark from
              the THEME's colours — which sets icon polarity and a few things
              no stylesheet reaches — so the theme has to agree with the
              palette even though custom.css does the real work. It also means
              the look survives with CSS modifications switched off.
              **Only while Vivaldi is closed**: it rewrites Preferences from
              memory on exit, so a write underneath a running browser is
              discarded. This refuses rather than lose the edit.

              The load-bearing part is NOT `themes.current`, which on its own
              is ignored at startup — measured on 8.1 against both a generated
              id and a built-in one, with `themes.system` present and absent.
              What the theme engine actually reads is `vivaldi.theme.schedule`
              (`o_s.light` / `o_s.dark`), so this writes the id into both and
              leaves `enabled` at 0. If he has scheduling switched ON, that map
              is his and this refuses to touch it.

    apps/pylib/tools/vivaldi-theme.py             # both (prefs if it can)
    apps/pylib/tools/vivaldi-theme.py --ui
    apps/pylib/tools/vivaldi-theme.py --prefs
    apps/pylib/tools/vivaldi-theme.py --css       # print, write nothing
    apps/pylib/tools/vivaldi-theme.py --source hypr|plasma
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import scrollcss                                                # noqa: E402
import vivaldichrome                                            # noqa: E402

DATA = Path(os.environ.get("XDG_DATA_HOME") or (Path.home() / ".local" / "share"))
UI_DIR = Path(os.environ.get("VIVALDI_UI_DIR") or (DATA / "vivaldi-ui"))
PREFS = Path(os.environ.get("VIVALDI_PREFS")
             or (Path.home() / ".config" / "vivaldi" / "Default" / "Preferences"))
THEME_ID = "desktop-live"

HEADER = """\
/* Vivaldi wearing this desktop's look — %s.
 *
 * Generated by ~/nix/apps/pylib/tools/vivaldi-theme.py — do not hand-edit,
 * re-run it (the vivaldi-ui-css path unit does, on every palette change).
 * Read at Vivaldi STARTUP only: a change here shows at the next launch.
 */
"""


def build_css(source=None, style=None):
    bar, barprov = scrollcss.build(source, style)
    css, prov = vivaldichrome.build(source, extra=bar)
    return css, "%s; scrollbar: %s" % (prov, barprov)


def write_ui(source=None, style=None, directory=UI_DIR):
    css, prov = build_css(source, style)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "custom.css"
    text = HEADER % prov + css + "\n"
    # Unchanged content is not rewritten: the path unit calls this on every
    # palette write, and a quiet rewrite would only churn the file's mtime.
    try:
        if path.read_text(encoding="utf-8") == text:
            return path, prov, False
    except OSError:
        pass
    path.write_text(text, encoding="utf-8")
    return path, prov, True


def vivaldi_running() -> bool:
    try:
        return subprocess.run(["pgrep", "-x", "vivaldi-bin"],
                              stdout=subprocess.DEVNULL).returncode == 0
    except OSError:
        return False


def write_prefs(source=None, prefs=PREFS, force=False):
    """Install the generated theme and make it current. Returns (path, changed)."""
    if vivaldi_running() and not force:
        raise SystemExit("vivaldi is running — it rewrites Preferences on exit, so this "
                         "write would be discarded. Close it and re-run (or --force).")
    try:
        data = json.loads(prefs.read_text(encoding="utf-8"))
    except OSError as e:
        raise SystemExit("no Vivaldi Preferences at %s (%s)" % (prefs, e))
    except ValueError as e:
        raise SystemExit("Preferences is not readable JSON (%s)" % e)

    import chansource
    import kdetheme
    plasma = kdetheme.is_plasma() if source is None else (source == "plasma")
    colors = kdetheme.kde_palette() if plasma else None
    pal = ({k: kdetheme._hex(v) for k, v in colors.items()} if colors
           else chansource.panel_palette())
    if not pal:
        raise SystemExit("no palette to build a theme from")

    entry = vivaldichrome.theme(pal.__getitem__)
    entry["id"] = THEME_ID
    vivaldi = data.setdefault("vivaldi", {})
    themes = vivaldi.setdefault("themes", {})
    user = themes.setdefault("user", [])
    if not isinstance(user, list):
        raise SystemExit("vivaldi.themes.user is not a list — refusing to touch it")
    # Replace ours in place; never disturb a theme he made himself.
    before = json.dumps([u for u in user if isinstance(u, dict) and u.get("id") == THEME_ID],
                        sort_keys=True)
    user = [u for u in user if not (isinstance(u, dict) and u.get("id") == THEME_ID)]
    user.append(entry)
    themes["user"] = user
    was_current = themes.get("current")
    themes["current"] = THEME_ID

    # `themes.current` alone does nothing at startup (measured). The engine
    # resolves the theme through the light/dark SCHEDULE map, so the id has to
    # be in there too — with `enabled` 0, which is "no scheduling", not "no
    # theme". A schedule he has actually switched on is his: leave it alone.
    schedule = vivaldi.setdefault("theme", {}).setdefault("schedule", {})
    if schedule.get("enabled"):
        raise SystemExit("Vivaldi's theme SCHEDULE is switched on — it owns which theme "
                         "applies when, and overwriting it would change that. Turn "
                         "scheduling off in Settings > Themes, or pick %r there yourself."
                         % THEME_ID)
    was_map = dict(schedule.get("o_s") or {})
    schedule["enabled"] = 0
    schedule["o_s"] = {"dark": THEME_ID, "light": THEME_ID}
    changed = (before != json.dumps([entry], sort_keys=True)
               or was_current != THEME_ID
               or was_map != schedule["o_s"])
    if changed:
        prefs.write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")
    return prefs, changed


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", choices=("hypr", "plasma"),
                    help="force the palette source instead of the live session")
    ap.add_argument("--style", choices=scrollcss.STYLES,
                    help="force a desktop scrollbar variant instead of the settings pick")
    ap.add_argument("--ui", action="store_true", help="write only custom.css")
    ap.add_argument("--prefs", action="store_true", help="write only the theme entry")
    ap.add_argument("--css", action="store_true", help="print the css, write nothing")
    ap.add_argument("--force", action="store_true",
                    help="write Preferences even with Vivaldi running (it will be lost)")
    ap.add_argument("--dir", type=Path, default=UI_DIR)
    a = ap.parse_args()

    if a.css:
        sys.stdout.write(build_css(a.source, a.style)[0])
        return 0
    both = not (a.ui or a.prefs)
    if a.ui or both:
        path, prov, changed = write_ui(a.source, a.style, a.dir)
        print("%s\n  %s — %s\n  vivaldi://experiments -> allow CSS modifications, then"
              " Settings > Appearance > Custom UI Modifications = %s"
              % (path, "rewritten" if changed else "unchanged", prov, path.parent))
    if a.prefs or both:
        if both and vivaldi_running():
            print("Preferences: skipped, vivaldi is running (it would be overwritten "
                  "on exit). Close it and run: vivaldi-theme --prefs")
        else:
            path, changed = write_prefs(a.source, force=a.force)
            print("%s\n  theme %r %s and made current"
                  % (path, THEME_ID, "written" if changed else "already installed"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
