{ host, ... }:

# Tell every Claude Code session which of the two machines it is running on.
#
# The problem this fixes: an agent's environment block carries the working
# directory, `Platform: linux` and a kernel version string — and no hostname.
# The only tell that you are on `book` is `…asahi.fc44.aarch64…` buried in that
# string, and nothing reads it. So agents fall back on the repo's dominant
# voice — AGENTS.md is written from `top`'s point of view, with
# `sudo rebuild-top` presented as *the* rebuild command — and assume `top`. On
# the laptop that is wrong, and the wrong rebuild command is the least of it.
#
# Why this cannot be a file under ~/.claude: that whole tree syncs both ways
# between the machines (home/srvs/claude-state.nix). A note there saying "you
# are on book" is read on `top` and is false there; `top`'s agent corrects it,
# the correction syncs back, and the two machines take turns being wrong. That
# loop is the actual bug — the fact cannot live in a synced file. The same
# argument rules out docs/ (home/srvs/nix-docs.nix syncs it too).
#
# So it is generated here, per machine, into ~/.config — which syncs nowhere —
# and injected at session start by the `SessionStart` hook in
# ~/.claude/settings.json. settings.json *is* synced, and that is fine: it
# names a path, not an answer, and the path resolves differently on each host.
#
# `host` is the flake attribute ("top" | "air"), threaded in by flake.nix. The
# OS hostname of the `air` machine is `book`; both names are correct, for
# different things (docs/HARDWARE.md). The script prints the live `hostname`
# too, so a generation activated from the wrong host shows up instead of
# quietly asserting the wrong identity.

let
  isAir = host == "air";

  osName = if isAir then "book" else "top";
  arch = if isAir then "aarch64 Fedora Asahi Remix, home-manager only" else "x86_64 NixOS";
  rebuild = if isAir then "home-manager switch --flake ~/nix#air" else "sudo rebuild-top";
  scope =
    if isAir then
      "`sys/` does not apply here; there is no `hosts/air/`."
    else
      "Full NixOS: both `sys/` and `home/` apply.";
in
{
  xdg.configFile."scripts/claude-host-id.sh" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      # Generated by home/prog/claude-host-id.nix — do not edit here.
      # Emitted into every Claude Code session as SessionStart context.
      set -u

      # SINGLE-quoted args, deliberately: the text is full of backticks
      # (`air`, `sys/`) and inside double quotes the shell runs each of them as
      # a command substitution — which is what the first version of this script
      # did, printing "sys/: Is a directory" into every session. Keep every
      # literal below free of apostrophes for the same reason.
      printf '%s\n' \
        'HOST ${osName} | flake attr `${host}` | ${arch}' \
        'Rebuild: ${rebuild}' \
        '${scope}' \
        'You are NOT on the other machine. Never write "this machine" or' \
        '"you are on X" into docs/, AGENTS.md or a memory — those trees sync' \
        'to the other host, where the sentence is false. Name the host.'

      live=$(hostname 2>/dev/null || true)
      if [ -n "''${live:-}" ] && [ "$live" != "${osName}" ]; then
        printf '%s\n' "WARNING: live hostname is '$live', but this home-manager" \
                      "generation was built for '${osName}'. Trust hostname."
      fi
    '';
  };
}
