#pragma once

#define WLR_USE_UNSTABLE

#include <hyprland/src/devices/IPointer.hpp>
#include <hyprland/src/desktop/DesktopTypes.hpp>
#include <hyprland/src/helpers/signal/Signal.hpp>
#include <hyprland/src/managers/eventLoop/EventLoopTimer.hpp>

#include <array>
#include <chrono>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace Event {
    struct SCallbackInfo;
}
class CWLSurfaceResource;

// macOS-style momentum ("kinetic") scrolling, desktop-wide.
//
// macOS momentum is generated by the OS, not by apps — apps just receive scroll
// events tagged with a momentum phase. The only layer of this desktop that can
// do the same thing for GTK, Qt, Chromium and the in-house suite at once is the
// compositor, which is why this lives in a Hyprland plugin and not in QML.
//
// The mechanism, in one paragraph: this module watches finger-source axis
// events on the event bus and keeps a short ring of them. libinput GUARANTEES
// that a FINGER scroll sequence is terminated by an event with delta == 0
// (/usr/include/libinput.h:1679 — "A caller may use this information to decide
// on whether kinetic scrolling should be triggered on this scroll sequence"),
// so that zero is the finger-lift. When it arrives, this module estimates the
// velocity, SWALLOWS the stop (`info.cancelled = true`, so the client never
// learns the gesture ended) and starts emitting exponentially decaying axis
// events on a timer, straight at the seat.
//
// Five design points that are not obvious and are expensive to rediscover:
//
//  1. Emission goes to CSeatManager::sendPointerAxis, NEVER through
//     CInputManager::onMouseWheel. The seat call sits DOWNSTREAM of the
//     `input.mouse.axis` bus, so synthetic events cannot re-enter this
//     estimator, any decoration's handler (the PLAYBAR seeks per event — a
//     60-tick coast would jump a song by minutes), or any keybind. The guard is
//     structural, not a flag. onMouseWheel is separately disqualified: for
//     FINGER it defers the wl_pointer.frame to a device frame a timer does not
//     have, and the pending flag is private, so the client would buffer the
//     axis forever.
//
//  2. The source tag is WL_POINTER_AXIS_SOURCE_FINGER, never CONTINUOUS. Qt
//     only opens a scroll phase for finger (`isDefinitelyTerminated` is
//     literally `src == 1`, confirmed by disassembling the installed
//     libQt6WaylandClient), GDK maps CONTINUOUS to TRACKPOINT which drops
//     Firefox out of its pan path, and Chromium's velocity regression breaks on
//     any non-FINGER frame.
//
//  3. A value == 0.0 send IS the protocol axis_stop. Never emit one mid-flight;
//     that is what the fractional carry below exists for. See the GUARD note on
//     Hl::sendAxis.
//
//  4. The terminal stop is WITHHELD for stop_delay_ms (300) after the last
//     synthetic delta. Every client-side fling estimator gates on the stop and
//     has a SHORTER window than that (Chromium 200 ms, GTK 150, kitty 150,
//     Firefox 100), so all of them compute exactly zero velocity and
//     double-fling becomes provably impossible rather than "probably small".
//
//  5. A fling cannot be latched to its target. sendPointerAxis takes no surface
//     argument — it always sends to whatever has pointer focus right now. So
//     the latch below is for VALIDATION only: when focus moves, the fling is
//     dropped rather than redirected. (macOS does latch; we cannot, and
//     spraying momentum into the wrong client is the classic X11 coasting bug.)
//
// Ships DISABLED (`plugin:hyprvtb:kinetic = false`). Turn it on for a session
// with `hyprctl eval "hl.plugin.hyprvtb.kinetic_set(true)"`, which also makes
// `hyprctl reload` the rollback.
class CVtbKinetic {
  public:
    CVtbKinetic() = default;
    // Runs shutdown() if PLUGIN_EXIT somehow did not: the tick's code lives in
    // this .so, so the timer must never outlive the object that owns it.
    ~CVtbKinetic();

    // ---- feeds -------------------------------------------------------------

    // THE hook: one global listener on input.mouse.axis. Samples finger deltas,
    // and turns the terminating zero into a fling if every gate agrees.
    void onAxis(const IPointer::SAxisEvent& e, Event::SCallbackInfo& info);
    // Per-device frame: belt-and-braces finger-lift detection for the case
    // where the guaranteed terminating zero does not show up. Takes the device
    // it came from, so one touchpad's frame cannot consume another's evidence.
    void onDeviceFrame(uintptr_t devId);
    // Per-device hold-begin: fingers back on the pad. This is the brake, and it
    // is reachable ONLY per device — the event bus has swipe and pinch but no
    // hold on either pin.
    void onHoldBegin();

    // Cancellation feeds, all wired from main.cpp's existing listener block.
    void onPointerButton();
    void onKeyboardKey();
    void onGestureBegin();
    void onPointerFocusChange();
    void onConfigReloaded();

    // Called from main.cpp's 150ms heartbeat. The pointer device list has NO
    // add/remove event on either pin, so the per-device listeners have to be
    // re-derived by polling a cheap fingerprint of it.
    void heartbeat();

    // PLUGIN_EXIT. Stops deciding, drops the timer and the listeners, and only
    // THEN flushes what the client is owed — in that order, so nothing can
    // re-arm into an image that is about to be unmapped.
    void shutdown();

    // ---- lua surface (see main.cpp's luaKinetic* wrappers) -----------------

    bool        setEnabled(bool on);
    bool        setKnob(const std::string& key, double val);
    int         injectTest(double dy, int n, int ms, bool wet);
    void        cancelNow();
    std::string dumpJson();
    std::string statsJson();
    std::string getJson();

  private:
    // ---- phases ------------------------------------------------------------
    // IDLE     nothing happening; the timer is disarmed.
    // TRACKING a finger scroll is in progress; samples are accumulating.
    // FLYING   the finger is off and we are emitting a decaying tail.
    // GRACE    the tail is over; waiting out stop_delay_ms before the terminal
    //          axis_stop, so no client can build its own fling on top of ours.
    enum ePhase : uint8_t { KIN_IDLE = 0, KIN_TRACKING, KIN_FLYING, KIN_GRACE };

    // How a flight ends. STOP owes the client a terminal axis_stop (after the
    // grace, or immediately at PLUGIN_EXIT); DROP owes it nothing, because the
    // client has already had a wl_pointer.leave and sending axis events to a
    // surface that was left is a protocol violation.
    enum eEnd : uint8_t { KIN_END_STOP = 0, KIN_END_DROP };

    // 2D per timestamp: a diagonal touchpad frame arrives as TWO SAxisEvents
    // sharing one timeMs (aquamarine loops both axes then emits one frame), so
    // samples merge into the existing slot when the timestamp repeats.
    struct SSample {
        uint32_t tMs = 0;
        double   dx  = 0.0;
        double   dy  = 0.0;
    };
    static constexpr size_t KIN_SAMPLES = 16; // ~250ms of pad reports

    // The emit floor, in surface-local px. Qt turns pixelDelta into
    // `angleDelta = pixelDelta * -12` and drops the whole event when that
    // rounds to zero, so anything under 0.042 px vanishes in every Qt/QML app —
    // the entire in-house suite plus the panel. 0.10 is 2.4x that.
    static constexpr double KIN_EMIT_EPS = 0.10;

    // Ctrl | Alt | Super | Shift, in HL_MODIFIER_* space (IKeyboard.hpp:14-21).
    // Any of them held means the wheel means something else: surfer's Ctrl+wheel
    // zoom is x1.1 per event AND persisted on every step, so a coast under Ctrl
    // does not just look wrong, it writes 40 zoom levels to disk.
    static constexpr uint32_t KIN_MOD_MASK = (1 << 0) | (1 << 2) | (1 << 3) | (1 << 6);

    // What a fling is aimed at. Validated every tick, never redirected (5).
    struct SLatch {
        WP<CWLSurfaceResource> surface;
        PHLWINDOWREF           window;
        std::string            cls;
        bool                   isX11 = false;
    };

    struct SStats {
        uint64_t                  flings      = 0; // flings actually started
        uint64_t                  stopsSent   = 0; // terminal axis_stop sends
        uint64_t                  drops       = 0; // ended owing nothing
        uint64_t                  ticks       = 0;
        uint64_t                  emits       = 0; // axis events put on the wire (per axis, dry or wet)
        uint64_t                  emitRefused = 0; // MUST stay 0 — see Hl::sendAxis
        uint64_t                  lastEmits    = 0; // ...of the last flight only
        double                    lastDistance = 0.0;
        double                    lastV0       = 0.0;
        // Last gesture's observed cadence, which is the one thing about this
        // trackpad nobody has ever measured (it sets whether window_ms holds
        // enough samples for a stable sum/dt).
        uint32_t                  lastSamples    = 0;
        double                    lastCadenceMs  = 0.0;
        double                    lastSumAbsDelta = 0.0;
        std::map<std::string, uint64_t> refusals;  // start gate -> count
        std::map<std::string, uint64_t> cancels;   // cancel reason -> count
    };

    // ---- internals ---------------------------------------------------------
    void        pushSample(const IPointer::SAxisEvent& e);
    void        resetSamples();
    const char* startGate(uint32_t tStopMs, double& outVx, double& outVy, SLatch& outLatch);
    void        startFling(double vx, double vy, uint32_t tStopMs, const SLatch& latch);
    void        tick();
    void        armTick();
    void        disarm();
    void        emit(double outX, double outY);
    void        enterGrace();
    void        finishStop();
    void        endFlight(eEnd how, const char* reason);
    const char* verifyLatch();
    bool        classAllowed(const std::string& cls) const;
    void        rescanDevices();
    void        debugLog(int level, const std::string& msg);
    uint32_t    wireTime() const;
    double      period() const; // seconds per tick

    // effective (runtime override, else config) constants
    double eff(const char* key, double cfg) const;
    bool   effEnabled() const;
    double effFriction() const;
    double effMinStartVelocity() const;
    double effMinVelocity() const;
    double effMaxVelocity() const;
    double effGain() const;
    double effAxisLockRatio() const;
    int    effRateHz() const;
    int    effStopDelayMs() const;
    int    effWindowMs() const;
    int    effStaleMs() const;
    int    effMaxDurationMs() const;
    bool   effFrameStopFallback() const;
    int    effDebug() const;

    // ---- state -------------------------------------------------------------
    ePhase                          m_phase = KIN_IDLE;

    std::array<SSample, KIN_SAMPLES> m_ring{};
    size_t                          m_head  = 0; // next write slot
    size_t                          m_count = 0;

    double                          m_vx   = 0.0; // px/s, post scroll-factor
    double                          m_vy   = 0.0;
    double                          m_accX = 0.0; // fractional carry (3)
    double                          m_accY = 0.0;
    bool                            m_owedX = false; // client is owed a stop here
    bool                            m_owedY = false;

    SLatch                          m_latch;

    std::chrono::steady_clock::time_point m_t0{};        // fling start
    std::chrono::steady_clock::time_point m_lastTick{};
    std::chrono::steady_clock::time_point m_graceUntil{};
    std::chrono::steady_clock::time_point m_lastSampleAt{};
    uint32_t                              m_stopEventTimeMs = 0; // libinput clock continuity
    uint32_t                              m_lastSampleTimeMs = 0;
    uint64_t                              m_tickSeq = 0; // absolute schedule, no drift
    uint32_t                              m_startMods = 0; // KIN_MOD_MASK bits at fling start

    SP<CEventLoopTimer>                   m_timer;
    // The module MUST hold its own strong ref: CEventLoopManager::onTimerFire
    // skips any timer whose strongRef() is not > 2 (its own vector plus the
    // iteration copy make 2), so a timer nobody else owns silently never fires.

    std::vector<Hyprutils::Signal::CHyprSignalListener> m_devListeners;
    std::vector<uintptr_t>                             m_devFingerprint;

    // "Has an axis event arrived since this device's previous frame?", one entry
    // per touchpad. It has to be per device so that a second pointer's
    // motion-only frame cannot consume the evidence belonging to the touchpad
    // actually being scrolled. It can only ever be set for ALL of them at once,
    // though: the event bus carries no device on an axis event, so there is no
    // way to attribute one. See onDeviceFrame for what that leaves uncovered
    // and the config kill switch that answers it.
    std::map<uintptr_t, bool>                          m_devSawAxis;

    // Deduplicates the second stop event of a two-axis (diagonal) finger lift
    // when the FIRST one was refused: without it the same lift books two
    // refusals, and the second is always the meaningless "no-samples".
    uint32_t                                           m_lastStopTimeMs = 0;
    bool                                               m_haveLastStop   = false;

    std::map<std::string, double>                      m_overrides;
    bool                                               m_shuttingDown = false;
    bool                                               m_emitting     = false;

    // kinetic_test: dry runs record what WOULD have gone on the wire instead of
    // sending it. A wet run sprays real scroll at whatever the pointer happens
    // to be over, so it is refused unless explicitly unlocked in this process.
    //
    // m_dry is the load-bearing one, so its ownership is stated explicitly:
    // ONLY injectTest may write it, and only while m_injecting is true. Any
    // other writer is a hole — a dry invocation that ends up emitting real
    // events at the user's pointer focus is precisely the bug this pair now
    // makes structurally impossible (see injectTest and endFlight).
    bool                                               m_dry       = false;
    bool                                               m_injecting = false;
    bool                                               m_unsafeWet = false;
    std::vector<std::pair<uint32_t, double>>           m_trace;
    static constexpr size_t                            KIN_TRACE_MAX = 512;

    SStats                                             m_stats;
};
