"""Describe native Oxygen RGB correctly when exporting it to a browser.

Native SDR paint uses sRGB primaries with a gamma-2.2 transfer function.
An untagged PNG instead makes Chromium assume the sRGB transfer function.
Attach the native profile without converting pixels or altering the Qt raster.
This module is Qt-free because the browser courier runs in plain Python.
"""
import base64
import struct

# PNG iCCP chunk generated by Qt QColorSpace(SRgb, Gamma, 2.2).
# Includes the chunk length and CRC; the profile has no host/display metadata.
_GAMMA22 = base64.b64decode(
    'AAABCGlDQ1BDdXN0b20AABiVY2BgPMEABCwODAy5eSVFQe5OChGRUQoMSCAxubiAAS/4do2BEURf1g0sYePGrxYDcBUBLQTSf4BYJB3MZhQAsZMgbBUQu7ykoATItgCxkwuKQGwfIFspOSMxBcgGuU+nKCTIGcieA2QLpCOxk5DYKanFyUD2GiBbBuHP/PkMDBZfGBiYJyLEkqYxMGxvZ2CQuIMQU1nIwMDfysCw7TJC7LM/2O+MYodyc0qToX4CifCk5oUGA2k2kF0Mfgz6DI4MDMVpxkYQFTwODAysd////6zFwMA+iYHhb////78X/f//dzHQHbcYGA60FyQWJcJDicnYGIf5ICADALQ1SQ/hqYI9'
)


def browser_png(payload: bytes) -> bytes:
    """Return a gamma-2.2 tagged copy, preserving every compressed pixel byte."""
    signature = b"\x89PNG\r\n\x1a\n"
    if not payload.startswith(signature):
        raise ValueError("Oxygen surface is not a PNG")
    chunks = [signature]
    offset = len(signature)
    while offset < len(payload):
        if offset + 12 > len(payload):
            raise ValueError("truncated Oxygen PNG chunk")
        length = struct.unpack_from(">I", payload, offset)[0]
        end = offset + length + 12
        if end > len(payload):
            raise ValueError("truncated Oxygen PNG data")
        kind = payload[offset + 4:offset + 8]
        if kind not in (b"iCCP", b"sRGB", b"gAMA", b"cHRM"):
            chunks.append(payload[offset:end])
        if kind == b"IHDR":
            chunks.append(_GAMMA22)
        offset = end
    return b"".join(chunks)
