"""One Tampermonkey runtime, for every sheet this desktop puts into Vivaldi.

surfer wears these sheets natively, through its own url-scheme couriers.
Vivaldi is somebody else's browser: no Stylus, and the only injection seat is
Tampermonkey — so a sheet gets there as a userscript. There are two of them now
(the OneeChan 4chan re-skin and the desktop's scrollbar) and they want exactly
the same behaviour, so the behaviour lives here rather than in each generator:

* the sheet is EMBEDDED, as the fallback for a page loaded while the courier
  (`tools/chan-theme-server.py`, 127.0.0.1) is down,
* and then PULLED from that courier and re-adopted whenever its ETag moves, so
  a colour-scheme or wallpaper change repaints an open tab and no regeneration
  is needed at all,
* through `GM_xmlhttpRequest`, because a page is https and `http://127.0.0.1`
  is mixed content that a plain `fetch()` will not make,
* adopted via `adoptedStyleSheets`, which orders AFTER any document `<style>`
  — the cascade is what wins here, not specificity — with a `<style>` appended
  last as the fallback where constructable stylesheets are missing.

`gate` is the one difference between the two: the 4chan sheet must ride only
while OneeChan is actually on (`html.oneechan`), and the scrollbar rides
everywhere.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

# Long enough that an idle tab is doing nothing measurable, short enough that a
# palette change lands while he is still looking at the result.
POLL_SECONDS = 30

HEADER = """\
// ==UserScript==
// @name         %(name)s
// @namespace    https://github.com/meatcrowning/nix
// @version      %(version)s
// @description  %(description)s Generated by ~/nix/apps/pylib/tools/%(tool)s — do not hand-edit, re-run it.
// @author       lam
%(matches)s// @run-at       document-start
// @grant        GM_xmlhttpRequest
// @connect      127.0.0.1
// @connect      localhost
// @downloadURL  %(downloadURL)s
// @updateURL    %(updateURL)s
// ==/UserScript==
"""

BODY = r"""
(function(){
  'use strict';
  var KEY = %(key)s;
  if (window[KEY]) return;
  window[KEY] = true;

  var URL = %(url)s;
  var POLL = %(poll)d * 1000;
  var CSS = %(css)s;            // embedded fallback: the palette at bake time
  var GATE = %(gate)s;          // a class on <html> to wait for, or null
  var stamp = null;             // the courier's ETag for what is adopted now
  var sheet = null;
  var styleId = %(styleId)s;

  function apply(css){
    try {
      if (!sheet){
        sheet = new CSSStyleSheet();
        document.adoptedStyleSheets = document.adoptedStyleSheets.concat([sheet]);
      }
      sheet.replaceSync(css);
      return;
    } catch(e){}
    // No constructable stylesheets: a <style> appended LAST still lands after
    // the document's own sheets.
    try {
      var el = document.getElementById(styleId);
      if (!el){
        el = document.createElement('style');
        el.id = styleId;
        (document.head || document.documentElement).appendChild(el);
      }
      el.textContent = css;
    } catch(e2){}
  }

  // GM_xmlhttpRequest, not fetch: https page, http loopback courier.
  function pull(){
    var headers = stamp ? { 'If-None-Match': stamp } : {};
    try {
      GM_xmlhttpRequest({
        method: 'GET', url: URL, headers: headers, timeout: 4000,
        onload: function(r){
          if (r.status === 304) return;              // palette has not moved
          if (r.status !== 200 || !r.responseText) return;
          var tag = null;
          try {
            tag = /etag:\s*(\S+)/i.exec(r.responseHeaders || '');
            tag = tag && tag[1];
          } catch(e){}
          stamp = tag;
          apply(r.responseText);
        },
        onerror: function(){}, ontimeout: function(){}
      });
    } catch(e){}                                     // no grant: stay embedded
  }

  function start(){
    apply(CSS);                                      // never a frame unstyled
    pull();
    setInterval(pull, POLL);                         // live: repaint on change
  }

  if (!GATE){ start(); return; }

  function gated(){
    try {
      return !!(document.documentElement &&
                document.documentElement.classList.contains(GATE));
    } catch(e){ return false; }
  }

  // The gate is set after document-start (OneeChan marks the page when it
  // initialises), so poll for it and only then adopt. ~60s cap so a page that
  // is never going to carry it stops watching.
  var tries = 0;
  var iv = setInterval(function(){
    tries++;
    if (gated()){ clearInterval(iv); start(); }
    else if (tries > 600){ clearInterval(iv); }
  }, 100);
})();
"""


def source_version(sources, major=1):
    """A version that MOVES when the script does, and never goes backwards.

    Tampermonkey refuses an update whose version is not strictly newer, so a
    content hash cannot be used here: crc stamps have no order, and half of a
    palette change would read as a downgrade and be skipped in silence. This is
    the newest mtime of the files the script is built OUT of, in UTC, so it
    steps forward on an edit to the sheet, the generator or the runtime — and
    stands still for a palette change, which needs no reinstall (the script
    polls the courier for that).
    """
    stamps = [Path(p).stat().st_mtime for p in sources if Path(p).exists()]
    t = time.gmtime(max(stamps) if stamps else 0)
    return "%d.%s.%s" % (major, time.strftime("%Y%m%d", t), time.strftime("%H%M", t))


def build(*, name, description, matches, css, version, url, key, style_id,
          path, tool, gate=None, update_url=None):
    """The whole `.user.js` for one sheet."""
    # Tampermonkey never updates from a `file://` URL — the extension has no
    # file access and its updater refuses the scheme outright, which is why
    # this script sat at whatever version was installed by hand. The courier
    # already serves the sheet; it serves the SCRIPT from the same loopback
    # port, and the updater is a background fetch, so no mixed-content rule
    # applies to it.
    update_url = update_url or ("file://%s" % path)
    header = HEADER % {
        "name": name, "description": description, "version": version,
        "tool": tool, "path": path, "downloadURL": update_url,
        "updateURL": update_url,
        "matches": "".join("// @match        %s\n" % m for m in matches),
    }
    return header + BODY % {
        "key": json.dumps(key), "url": json.dumps(url), "poll": POLL_SECONDS,
        "css": json.dumps(css), "gate": json.dumps(gate),
        "styleId": json.dumps(style_id),
    }
