#!/usr/bin/env bash
# wal-set.sh — set a tiled wallpaper and recolour the whole desktop from it.
#
#   wal-set.sh [--wallpaper-only] [/path/to/wallpaper]
#
# With no argument it reapplies the last wallpaper (or wall.png). wal-prepare.sh
# supplies cached mode, tiles, and palette; this script publishes `current`,
# `current.mode`, and `current.blur` for Quickshell, then applies kitty,
# Hyprland, KDE/Qt, and cursor/RGB colours. Quickshell draws the wallpaper and
# cross-fades it; hyprpaper and its flash/offset workaround are gone.
#
# `--wallpaper-only` stops after publishing the three state files. Rewriting
# Theme.qml destroys/recreates the whole Quickshell tree, so the picker uses this
# two-phase path for instant previews and runs the full apply only on close.
#
# Everything is idempotent, so it is safe to run on every Hyprland start.
set -u

WALLPAPER_ONLY=0
if [ "${1:-}" = "--wallpaper-only" ]; then
    WALLPAPER_ONLY=1
    shift
fi

CONFIG="$HOME/.config"
CACHE="$HOME/.cache/wal"
SCRIPTS="$CONFIG/scripts"
STATE="$CACHE/current"
DEFAULT_WALL="$CONFIG/wall.png"
mkdir -p "$CACHE"

# ---- 1. resolve the wallpaper -------------------------------------------------
WALL="${1:-}"
if [ -z "$WALL" ]; then
    if [ -f "$STATE" ]; then WALL="$(cat "$STATE")"; else WALL="$DEFAULT_WALL"; fi
fi
if [ ! -f "$WALL" ]; then
    echo "wal-set: wallpaper not found: $WALL" >&2
    exit 1
fi
WALL="$(realpath "$WALL")"
printf '%s' "$WALL" > "$STATE"
echo "wal-set: wallpaper = $WALL"

# ---- 2. mode/tile/palette (delegated, cached — see wal-prepare.sh) -----------
"$SCRIPTS/wal-prepare.sh" "$WALL"
THEMES="$CACHE/themes"
KEY="$(printf '%s' "$WALL" | md5sum | cut -d' ' -f1)"
# shellcheck disable=SC1090
. "$THEMES/$KEY.mode"   # sets MODE, IW, IH

# ---- 2b. publish it for the panel to draw ------------------------------------
# The panel watches `current` (absolute path), `current.mode` (`tile`/`scale`),
# and `current.blur`. Publish them on every run, in place (same inode); an
# atomic rename would leave Quickshell watching the old file.
printf '%s' "$MODE" > "$STATE.mode"
# `current.blur` names wal-prepare.sh's cached backdrop; Quickshell falls back if
# it is missing or stale.
printf '%s' "$CACHE/blur-$KEY.png" > "$STATE.blur"

if [ "$WALLPAPER_ONLY" = 1 ]; then
    # Preview path: leave before palette work and its Theme.qml hot reload.
    echo "wal-set: wallpaper-only ($MODE), skipping theme apply"
    exit 0
fi

# ---- 3. load the palette (already extracted by wal-prepare.sh above) ---------
eval "$(cat "$THEMES/$KEY.env")"
echo "wal-set: source = ${IW}x${IH}, mode = $MODE, accent = #$ACCENT"

# Publish the quantised cluster list (dominant first, comma-separated bare hex)
# for the Settings swatch row (SetSwatches.qml) — the display the user picks
# palette colours from. In place, same inode rule as $STATE.mode above. An env
# cached before CLUSTERS existed publishes empty; the next re-extract fills it.
printf '%s' "${CLUSTERS:-}" > "$STATE.clusters"

# Theme.qml is deliberately last: its reload tears down the QML tree and can kill
# this picker-launched process. Apply kitty, borders, kdeglobals, cursor, and RGB
# first.

# ---- 4. kitty colours (reloaded via SIGUSR1) ---------------------------------
cat > "$CONFIG/kitty/theme.conf" <<KITTYEOF
# GENERATED by ~/.config/scripts/wal-set.sh from the current wallpaper.
# Normal text and the terminal's white slots are the palette's neutral reading
# pole (white on dark, black on light). Accent remains semantic.
foreground            #$TEXT
background            #$BG
cursor                #$ACCENT
cursor_text_color     #$BG
selection_foreground  #$BG
selection_background  #$ACCENT
url_color             #$ACCENT
active_border_color   #$ACCENT
inactive_border_color #$BORDER
active_tab_foreground   #$BG
active_tab_background   #$ACCENT
inactive_tab_foreground #$TEXTDIM
inactive_tab_background #$BGALT

# Monochrome ANSI ramp on the wallpaper's hue.
color0  #$BG
color8  #$DIM
color1  #$CRIT
color9  #$CRIT
color2  #$OK
color10 #$OK
color3  #$WARN
color11 #$WARN
color4  #$INFO
color12 #$INFO
color5  #$TEXTDIM
color13 #$TEXT
color6  #$ACCENT
color14 #$ACCENT
color7  #$TEXT
color15 #$TEXT
KITTYEOF

# make sure kitty.conf pulls in the generated file (once)
if ! grep -q '^include theme.conf' "$CONFIG/kitty/kitty.conf" 2>/dev/null; then
    printf '\ninclude theme.conf\n' >> "$CONFIG/kitty/kitty.conf"
fi
# live-reload every running kitty
pkill -USR1 -x kitty >/dev/null 2>&1

# ---- 4b. ly login greeter colours (read at his next login) ------------------
# /etc/ly/config.ini is a symlink to /var/lib/ly/config.ini, seeded from the
# NixOS module by sys/dsk/plasma.nix's activation; the six colour keys there
# are OURS to rewrite (the activation carries them forward across rebuilds),
# the rest is root-owned module state. No-op where the file does not exist
# (book). Must stay before step 7 like everything else — a quick local file
# write, but the Theme.qml reload tears the script down mid-run.
"$SCRIPTS/ly-theme.sh" "$ACCENT" "$DIM" "$CRIT"

# ---- 5. Hyprland focused-window border + hyprvtb titlebars (live + persisted)
# Lua config uses `hyprctl eval`, not `keyword`: update border/titlebar colours
# live in one call and persist them in the palette-tagged Nix source. Re-read
# user-owned shadow, title orientation, border width, rounding, and dim setting
# from settings.json so a theme/reload does not reset them.
SETTINGS="$CONFIG/quickshell/settings.json"
SHADOW_ALPHA=0.6
TITLE_ROTATED=false
BORDER_W=2
ROUNDING=0
if [ -f "$SETTINGS" ]; then
    v="$(sed -n 's/.*"shadowAlpha"[[:space:]]*:[[:space:]]*\([0-9.]*\).*/\1/p' "$SETTINGS" | head -n1)"
    [ -n "$v" ] && SHADOW_ALPHA="$v"
    # Preserve user-owned title orientation across reloads.
    grep -q '"titleOrientation"[[:space:]]*:[[:space:]]*"horizontal"' "$SETTINGS" && TITLE_ROTATED=true
    # Preserve the global border width and rounding.
    v="$(sed -n 's/.*"windowBorderWidth"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$SETTINGS" | head -n1)"
    [ -n "$v" ] && BORDER_W="$v"
    v="$(sed -n 's/.*"windowRounding"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$SETTINGS" | head -n1)"
    [ -n "$v" ] && ROUNDING="$v"
    # When dimming is disabled, the inactive border follows the new accent.
    grep -q '"dimUnfocused"[[:space:]]*:[[:space:]]*false' "$SETTINGS" && DIM_UNFOCUSED=false
fi
if [ "${DIM_UNFOCUSED:-true}" = false ]; then IB="${ACCENT}ee"; else IB="595959aa"; fi
hyprctl eval 'hl.config({
    general = { border_size = '"${BORDER_W}"', col = { active_border = "rgba('"${ACCENT}"'ee)", inactive_border = "rgba('"${IB}"')" } },
    decoration = { rounding = '"${ROUNDING}"' },
    plugin = { hyprvtb = {
        ["bg_color"]          = "rgba('"${BG}"'ff)",
        ["col.text"]          = "rgba('"${TEXT}"'ff)",
        ["col.button_border"] = "rgba('"${BORDER}"'ff)",
        ["col.accent"]        = "rgba('"${ACCENT}"'ff)",
        ["col.bg_alt"]        = "rgba('"${BGALT}"'ff)",
        ["col.crit"]          = "rgba('"${CRIT}"'ff)",
        ["col.warn"]          = "rgba('"${WARN}"'ff)",
        ["shadow_alpha"]      = '"${SHADOW_ALPHA}"',
        ["title_rotated"]     = '"${TITLE_ROTATED}"',
    } },
})' >/dev/null 2>&1
LUA="$CONFIG/hypr/hyprland.lua"
if [ -f "$LUA" ]; then
    sed -i -E 's/(\<active_border[[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${ACCENT}"'ee)\2/' "$LUA"
    sed -i -E 's/(^[[:space:]]*inactive_border[[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${IB}"')\2/' "$LUA"
    sed -i -E 's/(\["bg_color"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${BG}"'ff)\2/' "$LUA"
    sed -i -E 's/(\["col\.text"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${TEXT}"'ff)\2/' "$LUA"
    sed -i -E 's/(\["col\.button_border"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${BORDER}"'ff)\2/' "$LUA"
    sed -i -E 's/(\["col\.accent"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${ACCENT}"'ff)\2/' "$LUA"
    sed -i -E 's/(\["col\.bg_alt"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${BGALT}"'ff)\2/' "$LUA"
    sed -i -E 's/(\["col\.crit"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${CRIT}"'ff)\2/' "$LUA"
    sed -i -E 's/(\["col\.warn"\][[:space:]]*=[[:space:]]*")rgba\([0-9a-fA-F]+\)(")/\1rgba('"${WARN}"'ff)\2/' "$LUA"
    # Persist user-owned plugin settings so reload/restart agrees with live state.
    sed -i -E 's/(\["shadow_alpha"\][[:space:]]*=[[:space:]]*)[0-9.]+/\1'"${SHADOW_ALPHA}"'/' "$LUA"
    sed -i -E 's/(\["title_rotated"\][[:space:]]*=[[:space:]]*)(true|false)/\1'"${TITLE_ROTATED}"'/' "$LUA"
    # Anchor global frame replacements so examples and rounding_power do not match.
    sed -i -E 's/^([[:space:]]*border_size[[:space:]]*=[[:space:]]*)[0-9]+/\1'"${BORDER_W}"'/' "$LUA"
    sed -i -E 's/^([[:space:]]*rounding[[:space:]]+=[[:space:]]*)[0-9]+/\1'"${ROUNDING}"'/' "$LUA"
fi

# ---- 6. KDE / Qt apps (kdeglobals colours + pixel font; live-reloaded) --------
# Outside Plasma, update only the wallpaper-owned kdeglobals colour groups and
# notify running Qt apps; apply-pixel-font.sh owns the font keys. In Plasma,
# kdeglobals is the user's desktop theme, so re-mint the selected colour-scheme
# file instead of overwriting widget style, icons, or fonts.
KG="$CONFIG/kdeglobals"
# Oxygen's application art is raster and otherwise remains on its baked
# palette. Mint it off the critical path: recolouring the full icon set can take
# tens of seconds, but it must not hold the palette apply (or an app launch)
# hostage. The helper alternates its theme name and notifies KDE when done.
if command -v systemd-run >/dev/null 2>&1; then
    systemd-run --user --quiet --no-block --collect \
        --unit="wal-oxygen-icons-${ACCENT}" \
        "$SCRIPTS/oxygen-live-icons.py" --accent "$ACCENT" \
        >>"$CACHE/wallpaper-picker.log" 2>&1 \
        || setsid "$SCRIPTS/oxygen-live-icons.py" --accent "$ACCENT" \
            >>"$CACHE/wallpaper-picker.log" 2>&1 </dev/null &
else
    setsid "$SCRIPTS/oxygen-live-icons.py" --accent "$ACCENT" \
        >>"$CACHE/wallpaper-picker.log" 2>&1 </dev/null &
fi
PLASMA_SESSION=0
case ":$(printf '%s' "${XDG_CURRENT_DESKTOP:-}" | tr '[:lower:]' '[:upper:]'):" in
    *:KDE:*) PLASMA_SESSION=1 ;;
esac
if [ "$PLASMA_SESSION" = 1 ]; then
    # Keep the selected theme/shape; only move its colour family to the accent.
    echo "wal-set: Plasma session — KDE theme untouched, re-minting its colour scheme"
    if [ "$BG" = "464540" ]; then
        "$SCRIPTS/plasma-scheme.py" --accent "$ACCENT" --background "$BG" \
            --surface-color "$BGALT"
    else
        "$SCRIPTS/plasma-scheme.py" --accent "$ACCENT" \
            --surface-color "$BGALT"
    fi

    # ---- AeroThemePlasma glass ------------------------------------------
    # In the ATP session the titlebar and panel colour is NOT art: smod's frame
    # tiles are neutral greys (#212121 / #373737) and the colour arrives from
    # the aeroglassblur kwin effect, which colorizes the DECORATION region as
    # well as the window behind it. Its input is four ints in kwinrc — Win7's
    # "Window Color" panel, hue/saturation/brightness/intensity — so the
    # wallpaper accent reaches the whole chrome with a config write and no
    # asset work at all.
    #
    # Gated on the EFFECT being enabled, not on a session name: ATP's session
    # sets DesktopNames=KDE like every other Plasma session, so nothing in the
    # environment tells them apart, while `aeroglassblurEnabled` is true only
    # where ATP's own setup wizard has run.
    #
    # BlurEffect::reconfigure() reads the `kwinaero` shared-memory segment only
    # on its FIRST config and kwinrc on every one after, so kwriteconfig6 plus
    # one reconfigureEffect is the whole apply — there is no need to reproduce
    # the KCM's shared-memory writer.
    if command -v kwriteconfig6 >/dev/null 2>&1 && command -v kreadconfig6 >/dev/null 2>&1 \
       && [ "$(kreadconfig6 --file kwinrc --group Plugins --key aeroglassblurEnabled 2>/dev/null)" = "true" ]; then
        # accent hex -> HSV in the effect's own units (H 0-359, S/V 0-100).
        r=$((16#${ACCENT:0:2})); g=$((16#${ACCENT:2:2})); b=$((16#${ACCENT:4:2}))
        amax=$r; [ "$g" -gt "$amax" ] && amax=$g; [ "$b" -gt "$amax" ] && amax=$b
        amin=$r; [ "$g" -lt "$amin" ] && amin=$g; [ "$b" -lt "$amin" ] && amin=$b
        ad=$((amax - amin))
        if   [ "$ad" -eq 0 ];        then AH=0
        elif [ "$amax" -eq "$r" ];   then AH=$(( (60 * (g - b) / ad + 360) % 360 ))
        elif [ "$amax" -eq "$g" ];   then AH=$(( (60 * (b - r) / ad + 120) % 360 ))
        else                              AH=$(( (60 * (r - g) / ad + 240) % 360 ))
        fi
        AS=0; [ "$amax" -gt 0 ] && AS=$((100 * ad / amax))
        AV=$((100 * amax / 255))
        # A dark accent would make near-black glass, and Aero draws its titlebar
        # caption in BLACK — so floor the value. Hue and saturation pass through
        # untouched, which is what keeps a grey wallpaper's glass grey.
        [ "$AV" -lt 55 ] && AV=55
        # Intensity is how much of that colour is mixed in — his taste, not the
        # wallpaper's. Keep whatever the Window Color panel was left on.
        AI="$(kreadconfig6 --file kwinrc --group Effect-aeroglassblur --key AeroIntensity 2>/dev/null)"
        case "$AI" in ""|*[!0-9]*) AI=50 ;; esac
        for kv in "AeroHue $AH" "AeroSaturation $AS" "AeroBrightness $AV" "AeroIntensity $AI"; do
            kwriteconfig6 --file kwinrc --group Effect-aeroglassblur \
                --key "${kv%% *}" -- "${kv#* }"
        done
        dbus-send --session --dest=org.kde.KWin --type=method_call \
            /Effects org.kde.kwin.Effects.reconfigureEffect \
            string:aeroglassblur >/dev/null 2>&1 || true
        echo "wal-set: aero glass -> hue $AH sat $AS val $AV intensity $AI"
    fi
elif command -v kwriteconfig6 >/dev/null 2>&1; then
    hx() { printf '%d,%d,%d' "0x${1:0:2}" "0x${1:2:2}" "0x${1:4:2}"; }   # "rrggbb" -> "R,G,B"
    kw() { kwriteconfig6 --file "$KG" "$@"; }
    # group, background, foreground — the remaining roles are shared across groups.
    kdecolor() {
        local g="$1" bg="$2" fg="$3"
        kw --group "$g" --key BackgroundNormal    "$(hx "$bg")"
        kw --group "$g" --key BackgroundAlternate "$(hx "$BGALT")"
        kw --group "$g" --key ForegroundNormal    "$(hx "$fg")"
        kw --group "$g" --key ForegroundInactive  "$(hx "$TEXTDIM")"
        kw --group "$g" --key ForegroundActive    "$(hx "$ACCENT")"
        kw --group "$g" --key ForegroundLink      "$(hx "$ACCENT")"
        kw --group "$g" --key ForegroundVisited   "$(hx "$TEXTDIM")"
        kw --group "$g" --key ForegroundNegative  "$(hx "$CRIT")"
        kw --group "$g" --key ForegroundNeutral   "$(hx "$WARN")"
        kw --group "$g" --key ForegroundPositive  "$(hx "$OK")"
        kw --group "$g" --key DecorationFocus     "$(hx "$ACCENT")"
        kw --group "$g" --key DecorationHover     "$(hx "$ACCENT")"
    }
    # Every background is pure black (BG) to match the panel/kitty/rest of the
    # system — the Breeze style below draws flat, so nothing gradients away from
    # it. Only selections (accent) and the near-black alternate-row stripe
    # (BackgroundAlternate = BGALT, set inside kdecolor) break the black.
    #
    # Main copy is neutral high-contrast ink; accent stays for focus and
    # actions. Keep this in step with kitty and the custom-app Theme.text.
    kdecolor "Colors:Window"        "$BG"     "$TEXT"
    kdecolor "Colors:View"          "$BG"     "$TEXT"
    kdecolor "Colors:Button"        "$BG"     "$TEXT"
    kdecolor "Colors:Selection"     "$ACCENT" "$BG"
    kdecolor "Colors:Tooltip"       "$BG"     "$TEXT"
    kdecolor "Colors:Complementary" "$BG"     "$TEXT"
    kdecolor "Colors:Header"        "$BG"     "$TEXT"
    # Window-manager title text is the same neutral ink as the body copy.
    kw --group WM --key activeBackground   "$(hx "$BG")"
    kw --group WM --key activeForeground   "$(hx "$TEXT")"
    kw --group WM --key inactiveBackground "$(hx "$BG")"
    kw --group WM --key inactiveForeground "$(hx "$TEXTDIM")"

    # Flat widget style (Breeze, not Oxygen's gradients/frames). The live
    # Oxygen icon theme is selected above; do not overwrite it here.
    kw --group KDE   --key widgetStyle "Breeze"

    # Same pixel font AND size as kitty (font_size 11 in kitty.conf), everywhere.
    # The font roles (and kitty + the hyprvtb titlebar) now follow the Settings
    # "pixel font" pick — apply-pixel-font.sh reads fontFamily/fontSize from
    # settings.json and writes them here, so whoever runs on login (wal-set.sh)
    # and whenever the pick changes (the panel) share one writer. kwriteconfig6
    # below only handles the colour groups; the font delegate lives out of the
    # wallpaper derive because it is a Settings value, not a wallpaper value.
    "$CONFIG/scripts/apply-pixel-font.sh" >/dev/null 2>&1 || true

    # Reload palette (0), fonts (1), style (2) and icons (4) in running KDE/Qt
    # apps without a relogin. Harmless if there's no session bus or no listeners.
    # (apply-pixel-font.sh already sent the fonts(1) notify; this catches the
    # colour/style/icon rates too.)
    if command -v dbus-send >/dev/null 2>&1; then
        for change in 0 2 4; do
            dbus-send --session --type=signal /KGlobalSettings org.kde.KGlobalSettings.notifyChange int32 "$change" int32 0 >/dev/null 2>&1 || true
        done
    fi
fi

# Wine and Ableton read their colours only at process startup. Mint their next
# startup theme after kdeglobals so Ableton gets the exact window/view surfaces
# the other desktop apps use. There is no attempt to repaint a running process.
if command -v ableton-theme >/dev/null 2>&1 \
   && [ -d "$HOME/.wine/drive_c/ProgramData/Ableton/Live 11 Suite" ]; then
    # `wine regedit` leaves winedevice.exe alive after its parent returns.
    # A wallpaper-watch oneshot waits for every process in its cgroup, which
    # turned a completed palette update into a 90-second timeout.  The theme
    # is only for Ableton's next launch, so run it in its own transient unit.
    if command -v systemd-run >/dev/null 2>&1; then
        systemd-run --user --quiet --no-block --collect \
            --unit="wal-ableton-${ACCENT}${BG}" ableton-theme \
            >>"$CACHE/wallpaper-picker.log" 2>&1 \
            || echo "wal-set: Ableton theme update could not start" >&2
    else
        ableton-theme || echo "wal-set: Ableton theme update failed" >&2
    fi
fi

# ---- 6b. Cursor: outline -> accent, core -> bg -------------------------------
# Recolour and apply the cursor detached: ImageMagick work must not delay the
# palette reload, and the process must survive that reload. cursor-recolor.sh
# serialises overlapping runs; the transient user unit keeps it alive after a
# systemd oneshot, with setsid as the manual fallback.
if command -v systemd-run >/dev/null 2>&1; then
    systemd-run --user --quiet --no-block --collect \
        --unit="wal-cursor-${ACCENT}${BG}" \
        "$SCRIPTS/cursor-recolor.sh" "$ACCENT" "$BG" "${XCURSOR_SIZE:-22}" \
        >>"$CACHE/wallpaper-picker.log" 2>&1 \
        || setsid "$SCRIPTS/cursor-recolor.sh" "$ACCENT" "$BG" "${XCURSOR_SIZE:-22}" \
            >>"$CACHE/wallpaper-picker.log" 2>&1 </dev/null &
else
    setsid "$SCRIPTS/cursor-recolor.sh" "$ACCENT" "$BG" "${XCURSOR_SIZE:-22}" \
        >>"$CACHE/wallpaper-picker.log" 2>&1 </dev/null &
fi

# ---- 6c. RGB hardware: DRAM sticks + motherboard headers on the accent -------
# RGB follows the same detached/reload-safe path; rgb-set.py honours
# rgbFollowTheme and is harmless when OpenRGB is unavailable.
setsid "$SCRIPTS/rgb-set.py" "$ACCENT" \
    >>"$CACHE/wallpaper-picker.log" 2>&1 </dev/null &

# ---- 7. Quickshell palette (spliced into Theme.qml; panel hot-reloads) -------
# MUST BE LAST: writing Theme.qml hot-reloads and can tear down this picker-launched
# process. Keep the same inode (truncate/rewrite; do not replace with `mv`) so
# Quickshell's file watcher continues to observe the palette.
THEME="$CONFIG/quickshell/Theme.qml"
BLOCK="$CACHE/palette.inc"
cat > "$BLOCK" <<QMLEOF
    readonly property color bg:        "#$BG"
    readonly property color bgAlt:     "#$BGALT"
    readonly property color border:    "#$BORDER"
    readonly property color accent:    "#$ACCENT"   // active / occupied
    readonly property color dim:       "#$DIM"      // empty & unviewed
    readonly property color text:      "#$TEXT"
    readonly property color textDim:   "#$TEXTDIM"
    readonly property color highlight: "#$HIGHLIGHT"   // selection bg
    readonly property color ok:        "#$OK"
    readonly property color warn:      "#$WARN"
    readonly property color crit:      "#$CRIT"
    readonly property color info:      "#$INFO"
QMLEOF
awk -v inc="$BLOCK" '
    /\/\/ >>> wal palette/ { print; while ((getline line < inc) > 0) print line; skip=1; next }
    /\/\/ <<< wal palette/ { skip=0 }
    !skip { print }
' "$THEME" > "$THEME.tmp" && cat "$THEME.tmp" > "$THEME" && rm -f "$THEME.tmp"

echo "wal-set: done."
