#!/usr/bin/env bash
# apply-pixel-font.sh — push the Settings "pixel font" pick (settings.json
# fontFamily/fontSize) out to the four surfaces that historically hardcoded the
# default face: kitty, the hyprvtb titlebar, the KDE/Qt system font
# (kdeglobals) and qutebrowser.
#
# The panel and the six Qt apps already read the pick live (Theme.qml /
# deskstyle.py), so this script closes the gap for the rest. It is run:
#   * at login — from hyprland.lua autostart (alongside wal-set.sh), so the
#     persisted pick is on screen before the first kitty/titlebar/KDE window;
#   * live when the pick changes — from the panel's SettingsApply.qml
#     (onFontFamilyChanged / onFontSizeChanged), so flipping the pick mid-
#     session re-propagates without a relog.
#
# Everything is idempotent, so running it more than once is harmless.
set -u

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
SETTINGS="$CONFIG/quickshell/settings.json"

# Resolve the pick, mirroring SettingsStore.qml defaults.
#
# NEVER GUESS ON A FAILED READ. This script is fired mid theme-apply (wal-set
# step 6), which is triggered by the very Settings change whose debounced
# settings.json write can still be in flight — a jq read that lands in that
# window fails, and the old fallthrough then actively PUSHED the default
# family, resetting the titlebar/kitty font to More Perfect on a colour
# change. A pick we cannot read is a pick we leave alone (docs/DESIGN.md
# §10.2): retry briefly, then exit without touching anything. The defaults
# below now only ever apply when settings.json genuinely does not exist yet.
FAMILY="More Perfect DOS VGA"
SIZE=15
if [ -f "$SETTINGS" ]; then
    if ! command -v jq >/dev/null 2>&1; then
        echo "apply-pixel-font: no jq on PATH; leaving fonts as they are" >&2
        exit 0
    fi
    ok=""
    for _ in 1 2 3 4 5; do
        if jq -e . "$SETTINGS" >/dev/null 2>&1; then ok=1; break; fi
        sleep 0.2
    done
    if [ -z "$ok" ]; then
        echo "apply-pixel-font: $SETTINGS unreadable; leaving fonts as they are" >&2
        exit 0
    fi
    FAMILY="$(jq -r '.fontFamily // "More Perfect DOS VGA"' "$SETTINGS" 2>/dev/null)"
    SIZE="$(jq -r '.fontSize // 15' "$SETTINGS" 2>/dev/null)"
    # guard against a hand-edited or corrupt value
    case "$SIZE" in ''|*[!0-9]*) SIZE=15 ;; esac
    case "$FAMILY" in ''|null) FAMILY="More Perfect DOS VGA" ;; esac
fi
# The Qt surfaces use kitty's resolved Oxygen Mono cell, not its nominal
# settings value.  Keep the compositor titlebar on that same 13px cell.
RENDER_SIZE="$SIZE"
[ "$FAMILY" = "Oxygen Mono" ] && RENDER_SIZE=$(( SIZE - 1 ))
# The kitty/kdeglobals/qutebrowser size is in POINTS, and the desktop's is in
# PIXELS (DESIGN §2.1: 15px == 11pt at 96 DPI). Convert, keeping the default
# exact (1080/96 = 11.25 -> 11).
PT=$(( (SIZE * 72) / 96 ))

# ---- 1. kitty --------------------------------------------------------------
# kitty.conf does `include font.conf` (added in kitty.nix); this generated file
# is the writable half that carries the pick. Rewritten in place and the running
# kitty told to reload.
KF="$CONFIG/kitty/font.conf"
# Leading. kitty takes the cell height straight from the face's ascent+descent,
# and the three faces disagree about how much blank the cell carries: the DOS
# ones draw a 13-row ink span inside a 16-row cell (~23% padding), while Botis
# declares ascent 5 + descent 1 — EXACTLY its 6-row glyph box, zero leading, so
# consecutive lines touch and a screenful reads vertically squished. Its cell is
# also near-square (advance 5 / height 6 = 0.83) against the DOS 9x16 (0.56),
# which compounds the same percept. Measured, not eyeballed: cap `H` ink is
# 0.70 wide/tall in More Perfect and 0.667 in Botis, so the LETTERFORMS match
# within 5% — only the line box differs. 130% restores the DOS faces' ~23%
# padding. Fixed here rather than in the font's own metrics (build-4x6.py)
# because those are load-bearing for the panel's 2x2-block grid at 15px.
LEADING=""
[ "$FAMILY" = "Botis 4x6" ] && LEADING="modify_font cell_height 130%"
# Phenex (the smooth cursive) needs no line here: its declared cell already
# carries ~16% air over the ink box (hhea 830/-330 vs ink 800/-300).
cat > "$KF.tmp" <<EOF
# GENERATED by ~/.config/scripts/apply-pixel-font.sh from settings.json
font_family $FAMILY
font_size $PT
$LEADING
EOF
mv "$KF.tmp" "$KF"
# kitty reloads config on SIGUSR1 (the same signal wal-set.sh uses for theme).
pkill -USR1 -x kitty >/dev/null 2>&1 || true

# ---- 2. hyprvtb titlebar ---------------------------------------------------
# Same live-config path wal-set.sh uses for the titlebar colours. The titlebar
# font_size is in PIXELS (matches the panel/Theme), unlike kitty's points, so
# the resolved render size is used here. Set via the running compositor; re-applied at
# each login by the autostart call, so it survives a restart without touching
# the seed-once hyprland.lua.
#
# font_smooth (plugin >= 3.21) rides along with the family: a smooth face
# (Phenex) must NOT get the plugin's hardcoded cairo ANTIALIAS_NONE — that
# option outranks the face's fontconfig AA rule, so the cursive rendered as a
# staircase on the bars. The flag comes from the generated font-faces.json
# (font.nix selectableFaces), never a family name hardcoded here.
SMOOTH=false
FACES="$CONFIG/quickshell/font-faces.json"
[ -f "$FACES" ] && SMOOTH="$(jq -r --arg f "$FAMILY" '.[$f].smooth // false' "$FACES" 2>/dev/null)"
case "$SMOOTH" in true|false) ;; *) SMOOTH=false ;; esac
TERMINAL_CELL=false
[ -f "$FACES" ] && TERMINAL_CELL="$(jq -r --arg f "$FAMILY" '.[$f].terminalCell // false' "$FACES" 2>/dev/null)"
case "$TERMINAL_CELL" in true|false) ;; *) TERMINAL_CELL=false ;; esac
hyprctl eval "hl.config({ plugin = { hyprvtb = { [\"font\"] = \"$FAMILY\", [\"font_size\"] = $RENDER_SIZE, [\"font_smooth\"] = $SMOOTH, [\"font_terminal_cell\"] = $TERMINAL_CELL } } })" >/dev/null 2>&1 || true
# Persist the four keys into hyprland.lua (same pattern as wal-set.sh's
# shadow_alpha/title_rotated): Hyprland AUTO-RELOADS its config whenever that
# file changes — and wal-set.sh seds the palette into it on EVERY theme apply —
# so a key living only in the runtime override above reverted to the C++
# default on every colour tweak. The titlebar font reset to More Perfect on
# every palette change until 2026-08-08 because of exactly this. Guarded seds:
# rewriting an already-correct line would itself fire that same autoreload.
LUA="$CONFIG/hypr/hyprland.lua"
if [ -f "$LUA" ]; then
    lua_kv() { # $1 = key, $2 = lua-formatted value
        sed -E 's/[[:space:]]+/ /g' "$LUA" | grep -qF "[\"$1\"] = $2," && return 0
        sed -i -E "s|(\[\"$1\"\][[:space:]]*=[[:space:]]*)[^,]*,|\1$2,|" "$LUA"
    }
    lua_kv font "\"$FAMILY\""
    lua_kv font_size "$RENDER_SIZE"
    lua_kv font_smooth "$SMOOTH"
    lua_kv font_terminal_cell "$TERMINAL_CELL"
fi
# refresh_fonts AFTER the family set (plugin >= 3.19): pango caches the
# process's font map, so a face INSTALLED after the compositor started
# (Phenex, 2026-08-08) never appeared on the bars — the pick silently fell
# back. The refresh re-reads fontconfig AND flushes every bar's cached
# textures (a font config change alone never invalidates them), so the bars
# repaint in the new face immediately.
hyprctl eval "hl.plugin.hyprvtb.refresh_fonts()" >/dev/null 2>&1 || true

# ---- 3. KDE/Qt system font (kdeglobals) ------------------------------------
# Same writer wal-set.sh uses for the colour groups; only the font role lines
# are touched here so groups owned elsewhere are left alone.
if command -v kwriteconfig6 >/dev/null 2>&1; then
    FSPEC="$FAMILY,$PT,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
    for k in font menuFont toolBarFont smallestReadableFont fixed; do
        kwriteconfig6 --file "$CONFIG/kdeglobals" --group General --key "$k" "$FSPEC"
    done
    kwriteconfig6 --file "$CONFIG/kdeglobals" --group WM --key activeFont "$FSPEC"
    # Reload fonts (1) in running KDE/Qt apps without a relogin.
    if command -v dbus-send >/dev/null 2>&1; then
        dbus-send --session --type=signal /KGlobalSettings org.kde.KGlobalSettings.notifyChange int32 1 int32 0 >/dev/null 2>&1 || true
    fi
fi

echo "apply-pixel-font: family=$FAMILY size=${SIZE}px (${PT}pt)"
