"""Extract the original Unity shell and its runtime from the Quantal ISO."""

import hashlib
import os
from pathlib import Path
import re
import shutil
import sys


source, target = map(Path, sys.argv[1:])
records = {}
providers = {}
for paragraph in (source / "var/lib/dpkg/status").read_text().split("\n\n"):
    record = {}
    key = None
    for line in paragraph.splitlines():
        if line.startswith(" ") and key:
            record[key] += " " + line.strip()
        elif ": " in line:
            key, value = line.split(": ", 1)
            record[key] = value
    if record.get("Status") != "install ok installed":
        continue
    name = record["Package"]
    records[name] = record
    for provided in record.get("Provides", "").split(","):
        providers.setdefault(provided.strip().split(" ")[0], name)

roots = """
unity unity-services unity-lens-applications unity-lens-files
compiz-gnome gnome-settings-daemon gnome-control-center nautilus
indicator-appmenu indicator-application indicator-session indicator-sound
indicator-datetime indicator-messages notify-osd
light-themes humanity-icon-theme ubuntu-mono ubuntu-wallpapers ubuntu-sounds
ttf-ubuntu-font-family python dbus-x11 dconf-tools bash dash coreutils
""".split()
selected = set()
pending = list(roots)
while pending:
    name = pending.pop()
    if name in selected:
        continue
    record = records[name]
    selected.add(name)
    for group in (record.get("Pre-Depends", "") + "," + record.get("Depends", "")).split(","):
        if not group.strip():
            continue
        options = [re.split(r"[\s(:]", p.strip())[0] for p in group.split("|")]
        resolved = next((p for p in options if p in records), None)
        resolved = resolved or next((providers[p] for p in options if p in providers), None)
        if resolved is None:
            raise RuntimeError(f"Unresolved dependency of {name}: {group}")
        pending.append(resolved)


def copy_file(relative):
    src = source / relative
    dst = target / relative
    if src.is_dir() and not src.is_symlink():
        dst.mkdir(parents=True, exist_ok=True)
    elif src.exists() or src.is_symlink():
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists() or dst.is_symlink():
            return
        if src.is_symlink():
            dst.symlink_to(os.readlink(src))
        else:
            shutil.copyfile(src, dst)
            dst.chmod(src.stat().st_mode & 0o777)


for name in sorted(selected):
    lists = list((source / "var/lib/dpkg/info").glob(name + ".list"))
    lists += list((source / "var/lib/dpkg/info").glob(name + ":*.list"))
    if len(lists) != 1:
        raise RuntimeError(f"Expected one package manifest for {name}: {lists}")
    for filename in lists[0].read_text().splitlines():
        relative = filename.lstrip("/")
        if relative and relative != ".":
            copy_file(relative)

# These files are generated by package installation rather than listed as
# package payloads. Preserve the ISO's compiled schemas and theme defaults.
for directory in ["etc/fonts", "etc/compizconfig", "usr/share/glib-2.0/schemas", "usr/share/mime"]:
    for src in (source / directory).rglob("*"):
        copy_file(str(src.relative_to(source)))
for filename in ["etc/nsswitch.conf", "etc/ld.so.conf", "etc/lsb-release"]:
    copy_file(filename)
for pattern in ["loaders.cache", "immodules.cache", "giomodule.cache"]:
    for src in (source / "usr/lib").rglob(pattern):
        copy_file(str(src.relative_to(source)))
for src in (source / "etc/alternatives").iterdir():
    copy_file(str(src.relative_to(source)))

# Verify the fidelity-critical files against the ISO's package manifests.
for name in ["unity", "compiz-core", "libnux-3.0-0", "unity-asset-pool", "unity-common"]:
    manifests = list((source / "var/lib/dpkg/info").glob(name + ".md5sums"))
    manifests += list((source / "var/lib/dpkg/info").glob(name + ":*.md5sums"))
    for manifest in manifests:
        for line in manifest.read_text().splitlines():
            digest, filename = line.split(None, 1)
            file = target / filename
            if hashlib.md5(file.read_bytes()).hexdigest() != digest:
                raise RuntimeError(f"Original package checksum mismatch: {filename}")

(target / "packages.tsv").write_text("".join(
    f"{name}\t{records[name]['Version']}\n" for name in sorted(selected)
))
for directory in ["etc/profiles", "usr/local/bin", "usr/share/applications", "lib64", "var/lib/dbus"]:
    (target / directory).mkdir(parents=True, exist_ok=True)
for filename in ["etc/passwd", "etc/group", "etc/machine-id", "etc/localtime", "var/lib/dbus/machine-id"]:
    file = target / filename
    if not file.exists() and not file.is_symlink():
        file.touch()
for name in ["gnome-session-quit", "gnome-screensaver-command", "xdg-open"]:
    file = target / "usr/bin" / name
    if file.exists() or file.is_symlink():
        file.unlink()
    file.symlink_to("/usr/local/bin/" + name)
