[general]
bars = 16
framerate = 120
autosens = 1
lower_cutoff_freq = 30
higher_cutoff_freq = 16000

[smoothing]
noise_reduction = 0
monstercat = 1.5

[output]
method = raw
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10
